---
title: "tableone metastatic"
author: "Noah Lepola"
date: "2024-12-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tableone)
library(tidyverse)

```


#Loading files
```{r}
met_char <-  readRDS(file = "../Outputs/met_cohort_char.RData")
met_outcomes <-  readRDS(file = "../Outputs/met_cohort_outcomes.RData")

```


#Combining everything to be used in the table
```{r}
met_char_status <- full_join(met_outcomes, met_char)

met_char_status <- met_char_status %>% select(!Sample)
```

#Splitting data to be used in different outcome tables
```{r}
tc.tox <-filter(met_char_status, `Reason.for.discontinuation` == 
      "Therapy complete" | `Reason.for.discontinuation` == "Toxicity") 

tc.rec <-filter(met_char_status, `Reason.for.discontinuation` ==
      "Therapy complete" | `Reason.for.discontinuation` == "Progression")
```

#Creating objects for first table
```{r}
vars <- c("Sex", "Reason.for.discontinuation", "Age", "BMI (kg/m2)", "LDH (U/L)",
           "Stage", "Therapy")
```


#Making Table One separated by cohort
```{r}
met_char_status[met_char_status$Reason.for.discontinuation != "Therapy complete" & met_char_status$Reason.for.discontinuation != "Toxicity" & met_char_status$Reason.for.discontinuation != "Progression", "Reason.for.discontinuation"] <- "Other"

met_char_status[met_char_status$Cohort == "Met Validation", "Cohort"] <- "Validation"
met_char_status[met_char_status$Cohort == "Met Discovery", "Cohort"] <- "Exploratory"


cohort.strat <- CreateTableOne(vars = vars, strata = "Cohort",
                               data = met_char_status, test = TRUE)
cohort.strat

knitr::kable(print(cohort.strat, showAllLevels = TRUE))
```

