---
title: "tc vs pro demographics testing"
author: "Noah Lepola"
date: "2024-01-24"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(openxlsx)
library(broom)

knitr::opts_knit$set(root.dir = "T:/Labs/Burd/CEBurd Lab/Noah Lepola/Coding/my adjing work folder/Scripts for paper/Saved files for paper")


```

Loading file
```{r}
load(file = "../Outputs/gene.exp")
load(file = "../Outputs/pt.char")
load(file = "../Outputs/pt.status")
```
Splitting by cohort and outcome
```{r}
tc.tox.outcomes.adj <- filter(pt.status, Cohort == "Adj", Reason.for.discontinuation == "Therapy complete" | Reason.for.discontinuation == "Toxicity")
tc.tox.outcomes.val <- filter(pt.status, Cohort == "Adj Validation", Reason.for.discontinuation == "Therapy complete" | Reason.for.discontinuation == "Toxicity")
tc.tox.data.adj <- filter(pt.char, (Sample %in% tc.tox.outcomes.adj$Sample))
tc.tox.data.val <- filter(pt.char, (Sample %in% tc.tox.outcomes.val$Sample))
```


```{r}
#renaming column and merging 
tc.tox.df.adj <- left_join(tc.tox.outcomes.adj, tc.tox.data.adj, by = c("Sample" = "Sample" ))
tc.tox.df.val <- left_join(tc.tox.outcomes.val, tc.tox.data.val, by = c("Sample" = "Sample" ))


# Get a vector of column names
names <- colnames(tc.tox.df.val[, 4:9])
fixed.names <- make.names(colnames(tc.tox.df.val[, 4:9]))

#adding numbers for outcome
tc.tox.df.adj <- tc.tox.df.adj %>% mutate(Outcome = case_when(
  Reason.for.discontinuation == "Therapy complete" ~ 1,
  TRUE ~ 0))
tc.tox.df.val <- tc.tox.df.val %>% mutate(Outcome = case_when(
  Reason.for.discontinuation == "Therapy complete" ~ 1,
  TRUE ~ 0))

#renaming columns to ones that don't produce an error
fixed.tc.tox.df.adj <- tc.tox.df.adj %>% 
  rename_with(~ fixed.names[which((names) == .x)], .cols = any_of(names))
fixed.tc.tox.df.val <- tc.tox.df.val %>% 
  rename_with(~ fixed.names[which((names) == .x)], .cols = any_of(names))

#create dataframe to store the output 
tox_split_chr_adj <- (data.frame(characteristic = names,
                   estimate = NA,
                   p.value = NA))
tox_split_chr_val <- (data.frame(characteristic = names,
                   estimate = NA,
                   p.value = NA))

char.outcome.adj <- fixed.tc.tox.df.adj %>%
  select(-Sample, -Reason.for.discontinuation) 
char.outcome.val <- fixed.tc.tox.df.val %>%
  select(-Sample, -Reason.for.discontinuation) 


```

```{r}

for (g in 1:length(fixed.names)) {
  f <- as.formula(paste0("Outcome ~ ",fixed.names[g]))
   tmp <- glm(formula = f, data = char.outcome.adj, family = binomial)
   tmpdf <- broom::tidy(tmp)
#  retrieve the line of interest with g, estimate, and p-value
   tox_split_chr_adj$estimate[g] <- tmpdf$estimate[2]
   tox_split_chr_adj$p.value[g] <- tmpdf$p.value[2]
 
}
tox_split_chr_adj <- tox_split_chr_adj %>%
   mutate(FDR = p.adjust(p.value)) %>%
   arrange(FDR) 

save(tox_split_chr_adj, file = "../Outputs/tox_split_chr_adj")




for (g in 1:length(fixed.names)) {
  f <- as.formula(paste0("Outcome ~ ",fixed.names[g]))
   tmp <- glm(formula = f, data = char.outcome.val, family = binomial)
   tmpdf <- broom::tidy(tmp)
#  retrieve the line of interest with g, estimate, and p-value
   tox_split_chr_val$estimate[g] <- tmpdf$estimate[2]
   tox_split_chr_val$p.value[g] <- tmpdf$p.value[2]
 
}
tox_split_chr_val <- tox_split_chr_val %>%
   mutate(FDR = p.adjust(p.value)) %>%
   arrange(FDR) 

save(tox_split_chr_val, file = "../Outputs/tox_split_chr_val")

#might have a - sign. Will put to console, might want to assign it


#tc_samples <- subset(fixed.tc.pro.df, (fixed.tc.pro.df$Outcome == 1))
#prog_samples <- subset(fixed.tc.pro.df, (fixed.tc.pro.df$Outcome == 0))

#mean(tc_samples$BMI..kg.m2.)
#mean(prog_samples$BMI..kg.m2.)


```


