---
title: "adj_cohort_split_group_tox"
author: "Noah Lepola"
date: "2024-11-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(randomForest)
library(ROCR)

```

Loading file
```{r}
load(file = "../Outputs/gene.exp")
load(file = "../Outputs/pt.char")
load(file = "../Outputs/pt.status")
```
Splitting by cohort and outcome
```{r}
train.outcomes <- filter(pt.status, Cohort == "Adj", Reason.for.discontinuation == "Therapy complete" | Reason.for.discontinuation == "Toxicity")
train.outcomes <- filter(pt.status, Cohort == "Adj Validation", Reason.for.discontinuation == "Therapy complete" | Reason.for.discontinuation == "Toxicity")
train.seq <- filter(gene.exp, (Sample %in% train.outcomes$Sample))
test.seq <- filter(gene.exp, (Sample %in% test.outcomes$Sample))
```

Limiting information to just what is needed for this model and splitting outcome from expression
```{r}
train.seq.top <- train.seq %>% select(Sample, PDCD1LG2, NECTIN2)
test.seq.top <- test.seq %>% select(Sample, PDCD1LG2, NECTIN2)

top.c <- pt.char %>% select(Sample, Therapy)
train.seq.topc <- left_join(train.seq.top, top.c)
test.seq.topc <- left_join(test.seq.top, top.c)

train.outcomes <- train.outcomes %>% select(Sample, `Reason.for.discontinuation`)
test.outcomes <- test.outcomes %>% select(Sample, `Reason.for.discontinuation`)
```
Merging for total nanostring and outcomes
```{r}
total.seq <- full_join(train.seq, test.seq)
total.outcome <- full_join(train.outcomes, test.outcomes)
```


```{r}
k_validate <- function(total.outcome, total.seq, seed){
  set.seed(seed)
  

    out <- list()

      out[[1]] <- getROC(train.seq, train.outcomes, test.seq, test.outcomes)

  
  avg_aucpr <- lapply(out, function(x){ x[[1]]})
  message("\nAccuracy average: ", (rowMeans(as.data.frame(avg_aucpr))))
  return(out)
}
```

```{r}
# Function create and test RF model #
getROC <- function(train.seq, train.outcomes, test.seq, test.outcomes){
  model.training <- randomForest(x = train.seq[,-1, drop=FALSE], y = as.factor(train.outcomes$Reason.for.discontinuation))
  test.preds <- predict(model.training, test.seq[,-1, drop=FALSE])
  
  print(model.training)
  # Check variable importance
  varImpPlot(model.training)
  # Prediction confusion matrix
  table(observed = test.outcomes$Reason.for.discontinuation, predicted = test.preds)
  
  prediction_for_roc_curve <- predict(model.training, test.seq[,-1, drop=FALSE],type="prob")
  pred <- prediction(prediction_for_roc_curve[,2], test.outcomes$Reason.for.discontinuation, label.ordering = c("Therapy complete", "Toxicity"))
  perf <- performance(pred, "tpr", "fpr")
  
  aucpr_ROCR <- performance(pred, measure = "aucpr")
  print(aucpr_ROCR)
  aucpr <- aucpr_ROCR@y.values[[1]]
  print(aucpr)
  
  df <- data.frame(FalsePositive=c(perf@x.values[[1]]),
                   TruePositive=c(perf@y.values[[1]]))
  out <- list(aucpr, df)
  
  return(out)
}

```

```{r}
# Grabbing AUROC values from input models #
grabVals <- function(input){
  out <- list()
   for(i in 1:length(seed_list)){
      out <- append(out, input[[i]][[1]][[1]])
   }
  out
}
```

```{r}
# Main function call to generate RF models using 25 seeds #
kTest <- function(total.outcome, total.seq, seed_list){
  out <- list()
   for(i in 1:length(seed_list)){
    out[[i]] <- k_validate(total.outcome, total.seq, seed = seed_list[i])
   }
  out <- grabVals(out)
  
  # CW edit to function 
  out <- do.call(rbind.data.frame, out)
  colnames(out) <- c("AUCPR")
  out
}
```

```{r}
seed_list <- c(12345,12346,12347,12348,12349,12350,12351,12352,12353,12354,12355,12356,12357,12358,12359,12360,12361,12362,12363,12364,12365,12366,12367,12368,12369)
```

```{r}
#Currently working on this
r_tox_split_group_aucprs <- kTest(response, sampledata, seed_list) 
r_tox_split_group_aucprs_avg <- mean(r_tox_split_group_aucprs$AUCPR)
save(r_tox_split_group_aucprs, file = "../Outputs/r_tox_split_group_aucprs")
r_tox_split_group_aucprs_avg

```
