---
title: "adjing_cohort_split_rec_top_chr"
author: "Noah Lepola"
date: "2024-11-025"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(randomForest)
library(ROCR)



```

```{r}
load(file = "../Outputs/progression_val")
load(file = "../Outputs/complete_t_val")

load(file = "../Outputs/progression_adj")
load(file = "../Outputs/complete_t_adj")

load(file = "../Outputs/rec.tgc")

```


top ten genes by log regression VTCN1, CD160, GZMB, AHR, `IL-17A`, FOXO1, ITCH, BCL6, PVRIG, CD27
top 15 genes by log regression using only Adj (exploratory) cohort CD3D, HAVCR2, AHR, PVRIG, VTCN1, `KIR_Inhibiting_Subgroup_1`, CTLA4, CD28, `CDKN2A (ARF)`, CD274, CD244, CXCR3, ZBTB7B, GZMB, CD160
top characteristics using only Adj (exploratory) cohort `BMI (kg/m2)`, `LDH (U/L)`, Therapy, `Platelets (K/uL)`, Age, Stage, `Relative lymphocyte count (%)`



```{r}
k_validate <- function(treatment_outcome, patient_data, seed){
  set.seed(seed)
  

   #shuffling
  progression_val <- progression_val[sample(nrow(progression_val)), ]
  
  progression_adj <- progression_adj[sample(nrow(progression_adj)), ]
  

  #shuffling
  complete_t_val <- complete_t_val[sample(nrow(complete_t_val)), ]
  
  complete_t_adj <- complete_t_adj[sample(nrow(complete_t_adj)), ]

    # Creating index data frame for the progress/completed to ensure coverage for each group
    prog_indexes_val <- c(rep(1, 10))
    comp_indexes_val <- c(rep(1, 29))
    prog_indexes_adj <- c(rep(1, 12))
    comp_indexes_adj <- c(rep(1, 32))
    out <- list()
    
    # Creating testing and training groups #
    for(i in 1:1){
      pIndexes_val <- which(prog_indexes_val == i, arr.ind = TRUE)
      cIndexes_val <- which(comp_indexes_val == i, arr.ind = TRUE)
      pIndexes_adj <- which(prog_indexes_adj == i, arr.ind = TRUE)
      cIndexes_adj <- which(comp_indexes_adj == i, arr.ind = TRUE)
      
      test.outcomes <- rbind(complete_t_val[cIndexes_val, ], progression_val[pIndexes_val, ])
      train.outcomes <- rbind(complete_t_adj[cIndexes_adj, ], progression_adj[pIndexes_adj, ])
      
      test.seq <- rec.tgc[which(rec.tgc$Sample %in% test.outcomes$`Coded.Sample.#`), ]
      test.seq <- test.seq[match(test.outcomes$`Coded.Sample.#`, test.seq$Sample), ]
      
      train.seq <- rec.tgc[which(rec.tgc$Sample %in% train.outcomes$`Coded.Sample.#`), ]
      train.seq <- train.seq[match(train.outcomes$`Coded.Sample.#`, train.seq$Sample), ]
      
      if(all(train.seq$Sample == train.outcomes$`Coded.Sample.#`) == FALSE){
        stop("Training Sample_IDs do not match")
      }
      if(all(test.seq$Sample == test.outcomes$`Coded.Sample.#`) == FALSE){
        stop("Testing Sample_IDs do not match")
      }
      
      # Creating the RF model #
      out[[i]] <- getROC(train.seq, train.outcomes, test.seq, test.outcomes)
    }
  
  
  avg_aucpr <- lapply(out, function(x){ x[[1]]})
  message("\nAccuracy average: ", (rowMeans(as.data.frame(avg_aucpr))))
  return(out)
}
```

```{r}
# Function create and test RF model #
getROC <- function(train, outcomes.train, test, outcomes.test){
  model.training <- randomForest(x = train[,-1, drop=FALSE], y = as.factor(outcomes.train$Reason.for.discontinuation))
  test.preds <- predict(model.training, test[,-1, drop=FALSE])
  
  print(model.training)
  # Check variable importance
  varImpPlot(model.training)
  # Prediction confusion matrix
  table(observed = outcomes.test$Reason.for.discontinuation, predicted = test.preds)
  
  prediction_for_roc_curve <- predict(model.training,test[,-1, drop=FALSE],type="prob")
  pred <- prediction(prediction_for_roc_curve[,2], outcomes.test$Reason.for.discontinuation, label.ordering = c("Therapy complete", "Progression"))
  perf <- performance(pred, "tpr", "fpr")
  
  aucpr_ROCR <- performance(pred, measure = "aucpr")
  print(aucpr_ROCR)
  aucpr <- aucpr_ROCR@y.values[[1]]
  print(aucpr)
  
  df <- data.frame(FalsePositive=c(perf@x.values[[1]]),
                   TruePositive=c(perf@y.values[[1]]))
  out <- list(aucpr, df)
  
  return(out)
}

```

```{r}
# Grabbing AUROC values from input models #
grabVals <- function(input){
  out <- list()
  for(i in 1:25){
    for(j in 1:1){
      out <- append(out, input[[i]][[j]][[1]])
    }
  }
  out
}
```

```{r}
# Main function call to generate RF models using 5 seeds #
kTest <- function(outcome, data, seeds){
  out <- list()
  for(i in 1:length(seeds)){
    out[[i]] <- k_validate(outcomes, data, seed = seeds[i])
  }
  out <- grabVals(out)
  
  # CW edit to function 
  out <- do.call(rbind.data.frame, out)
  colnames(out) <- c("aucpr")
  out
}
```

```{r}
seed_list <- c(12345,12346,12347,12348,12349,12350,12351,12352,12353,12354,12355,12356,12357,12358,12359,12360,12361,12362,12363,12364,12365,12366,12367,12368,12369)
```

```{r}
#Currently working on this
r_rec_split_group_top12_chr_aucprs <- kTest(response, rec.tgc, seed_list) 
r_rec_split_group_top12_chr_aucprs_avg <- mean(r_rec_split_group_top12_chr_aucprs$aucpr)
save(r_rec_split_group_top12_chr_aucprs, file = "../Outputs/r_rec_split_group_top12_chr_aucprs")
r_rec_split_group_top12_chr_aucprs_avg

```
