---
title: "random_sample_rf_rec"
author: "Noah Lepola"
date: "2024-11-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(randomForest)
library(ROCR)



```

Loading file

```{r}
load(file = "../Outputs/gene.exp")
load(file = "../Outputs/pt.char")
load(file = "../Outputs/pt.status")
```

```{r}
source("../rec_functions.R")
```

Splitting by cohort and outcome

```{r}
train.outcomes <- filter(pt.status, 
                         Cohort == "Adj", 
                         Reason.for.discontinuation == "Therapy complete" | 
                        Reason.for.discontinuation == "Progression")
train.outcomes <- arrange(train.outcomes, desc(Sample))

test.outcomes <- filter(pt.status, 
                        Cohort == "Adj Validation", 
                        Reason.for.discontinuation == "Therapy complete" |
                        Reason.for.discontinuation == "Progression")
test.outcomes <- arrange(test.outcomes, desc(Sample))


train.seq <- filter(gene.exp, (Sample %in% train.outcomes$Sample))
train.seq <- arrange(train.seq, desc(Sample))


test.seq <- filter(gene.exp, (Sample %in% test.outcomes$Sample))
test.seq <- arrange(test.seq, desc(Sample))
```

Randomizing outcome

```{r}
run_number <- 1:10

r_random_rec_split_group_aucprs_avg <- data.frame(run = run_number, Average = NA)
```

```{r}
seed_list <- c(12345:12369)
```

```{r}
# train.seq <- train.seq %>% select(Sample, 
#  #                                  CD3D, HAVCR2, AHR, PVRIG, VTCN1,
#  # `KIR_Inhibiting_Subgroup_1`, CTLA4, CD28, `CDKN2A (ARF)`, CD274, CD244, CXCR3,
#  # ZBTB7B, GZMB, CD160, IFNG
# # PVRIG, BCL6
# VTCN1, CD160, NECTIN2
# # , `IL-21`
#  )
# 
# test.seq <- test.seq %>% select(Sample, 
#  #                                CD3D, HAVCR2, AHR, PVRIG, VTCN1,
#  # `KIR_Inhibiting_Subgroup_1`, CTLA4, CD28, `CDKN2A (ARF)`, CD274, CD244, CXCR3,
#  # ZBTB7B, GZMB, CD160, IFNG
# # PVRIG, BCL6
# VTCN1, CD160, NECTIN2
# # , `IL-21`
#  )
# 
# train.outcomes <- 
#   train.outcomes %>% 
#   select(Sample, `Reason.for.discontinuation`)
# 
# 
# test.outcomes <- 
#   test.outcomes %>% 
#   select(Sample,
#          `Reason.for.discontinuation`)
```



```{r}
for (j in 1:length(run_number)) {
  set.seed(seed_list[j])
train.outcomes$Reason.for.discontinuation<- 
  (sample(train.outcomes$Reason.for.discontinuation))

test.outcomes$Reason.for.discontinuation<- 
  (sample(test.outcomes$Reason.for.discontinuation))

r_random_rec_split_group_aucprs <- kTest(seed_list) 
avg <- mean(r_random_rec_split_group_aucprs$AUCPR)
r_random_rec_split_group_aucprs_avg[j, 2] <- avg

  }
mean(r_random_rec_split_group_aucprs_avg$Average)

```



