---
title: "svm"
author: "Noah Lepola"
date: "2025-01-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(e1071)
library(caret)

```


Loading files
```{r}
load(file = "../Outputs/xgb.char")
load(file = "../Outputs/pt.status")
load(file = "../Outputs/gene.exp")
```

joining everything to run in svm
```{r}
status.char <- left_join(pt.status, xgb.char)
status.char.exp <- left_join(status.char, gene.exp)


```

splitting into testing and training for therapy complete or recurrence
Removing StageI because svm can't handle all 0
```{r}
train <- filter(status.char.exp, Cohort == "Adj", 
Reason.for.discontinuation == "Therapy complete" |
  Reason.for.discontinuation == "Toxicity") %>% select(`Reason.for.discontinuation`, TNF, TGFB1)#, `IL-10`, `KIR_Inhibiting_Subgroup_2`, `KIR_Activating_Subgroup_2`)

test <- filter(status.char.exp, Cohort == "Adj Validation",
Reason.for.discontinuation == "Therapy complete" |
  Reason.for.discontinuation == "Toxicity") %>% select(`Reason.for.discontinuation`, TNF, TGFB1)#, `IL-10`, `KIR_Inhibiting_Subgroup_2`, `KIR_Activating_Subgroup_2`)

```


Converting to factor for use in svm
```{r}
train$Reason.for.discontinuation <- as.factor(train$Reason.for.discontinuation)
test$Reason.for.discontinuation <- as.factor(test$Reason.for.discontinuation)

```


```{r}
set.seed(12345)
```


```{r}

train.model <- svm(`Reason.for.discontinuation` ~ ., data = train, probability = TRUE, type = "C", class.weights=c("Toxicity"=0.238, "Therapy complete"=0.762))

test.model <- predict(train.model, test, probability = TRUE, type = "C", class.weights=c("Toxicity"=0.310, "Therapy complete"=0.690))
test.model.df <- data.frame(test.model)



confusionMatrix(test$Reason.for.discontinuation, test.model.df$test.model)

```




