---
title: "XGBoost_split_tox"
author: "Noah Lepola"
date: "2024-08-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(xgboost)
library(tidyverse)

```

Loading file
```{r}
load(file = "../Outputs/gene.exp")
load(file = "../Outputs/xgb.char")
load(file = "../Outputs/pt.status")
```


Splitting by cohort and outcome
```{r}
adj.char <- left_join(gene.exp, xgb.char,
                      by = join_by("Sample" == "Sample" ))

adj.outcomes <- filter(pt.status, 
                       Cohort == "Adj", 
                       Reason.for.discontinuation == "Therapy complete" | 
                         Reason.for.discontinuation == "Toxicity")

val.outcomes <- filter(pt.status, 
                       Cohort == "Adj Validation", 
                       Reason.for.discontinuation == "Therapy complete" |
                         Reason.for.discontinuation == "Toxicity")

g.and.c.data.adj <- filter(adj.char, (Sample %in% adj.outcomes$Sample))

g.and.c.data.val <- filter(adj.char, (Sample %in% val.outcomes$Sample))

val.data.outcomes <- left_join(val.outcomes,
                               g.and.c.data.val,
                               by = join_by("Sample" == "Sample" ))

adj.data.outcomes <- left_join(adj.outcomes,
                               g.and.c.data.adj,
                               by = join_by("Sample" == "Sample" ))

```


```{r}
train.data <- adj.data.outcomes %>%
  select(-Sample, -Reason.for.discontinuation, -Cohort)

train.label <- adj.data.outcomes %>%
  select(Reason.for.discontinuation) %>% 
  mutate(Reason.for.discontinuation = case_when(
  Reason.for.discontinuation == "Therapy complete" ~ 0, TRUE ~ 1))



test.data <- val.data.outcomes %>%
  select(-Sample, -Reason.for.discontinuation, -Cohort)

test.label <- val.data.outcomes %>%
  select(Reason.for.discontinuation) %>% 
  mutate(Reason.for.discontinuation = case_when(
  Reason.for.discontinuation == "Therapy complete" ~ 0, TRUE ~ 1))

xgb.train = xgb.DMatrix(data = as.matrix(train.data),
                        label = as.matrix(train.label))

xgb.test = xgb.DMatrix(data = as.matrix(test.data), 
                       label = as.matrix(test.label))


watchlist = list(train=xgb.train, test=xgb.test)

xgbtest = xgb.train(data = xgb.train, 
                    max.depth = 3, 
                    eta = 0.01,
                    watchlist = watchlist,
                    nrounds = 1000,
                    objective = "binary:logistic",
                    eval_metric = 'aucpr',
                    scale_pos_weight = 1,
                    early_stopping_rounds = 100)


importance_matrix <- xgb.importance(model = xgbtest)
print(importance_matrix)
xgb.plot.importance(importance_matrix = importance_matrix)

```


