---
title: "adjing_cohort_split_group_rec"
author: "Noah Lepola"
date: "2024-11-025"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(randomForest)
library(ROCR)

```

Loading file
```{r}
rm(list=ls())

load(file = "../Outputs/gene.exp")
load(file = "../Outputs/pt.char")
load(file = "../Outputs/pt.status")
```
Splitting by cohort and outcome

```{r}
source("../rec_functions.R")
```


```{r}
sorting <- function(data, cohort, outcome1, outcome2){
  filter(data, 
         Cohort == cohort, 
         Reason.for.discontinuation == outcome1 | 
           Reason.for.discontinuation == outcome2)  
}
  
train.outcomes <- sorting(pt.status,
                          "Adj",
                          "Therapy complete", 
                          "Progression")

train.outcomes <- arrange(train.outcomes, desc(Sample))


test.outcomes <- sorting(pt.status, 
                        "Adj Validation",
                        "Therapy complete",
                        "Progression")

test.outcomes <- arrange(test.outcomes, desc(Sample))


train.seq <- filter(gene.exp, (Sample %in% train.outcomes$Sample))
train.seq <- arrange(train.seq, desc(Sample))


test.seq <- filter(gene.exp, (Sample %in% test.outcomes$Sample))
test.seq <- arrange(test.seq, desc(Sample))


```

```{r}
train.seq <- train.seq %>% select(Sample,
 #                                  CD3D, HAVCR2, AHR, PVRIG, VTCN1,
 # `KIR_Inhibiting_Subgroup_1`, CTLA4, CD28, `CDKN2A (ARF)`, CD274, CD244, CXCR3,
 # ZBTB7B, GZMB, CD160, IFNG
# PVRIG, BCL6
VTCN1, CD160, NECTIN2
# , `IL-21`
 )

test.seq <- test.seq %>% select(Sample,
 #                                  CD3D, HAVCR2, AHR, PVRIG, VTCN1,
 # `KIR_Inhibiting_Subgroup_1`, CTLA4, CD28, `CDKN2A (ARF)`, CD274, CD244, CXCR3,
 # ZBTB7B, GZMB, CD160, IFNG
# PVRIG, BCL6
VTCN1, CD160, NECTIN2
# , `IL-21`
 )

train.outcomes <-
  train.outcomes %>%
  select(Sample, `Reason.for.discontinuation`)


test.outcomes <-
  test.outcomes %>%
  select(Sample,
         `Reason.for.discontinuation`)
```


```{r}
seed_list <- c(12345:12369)
```

```{r}
r_rec_split_group_aucprs <- kTest(seed_list) 
r_rec_split_group_aucprs_avg <- mean(r_rec_split_group_aucprs$AUCPR)
#save(r_rec_split_group_aucprs, file = "../Outputs/r_rec_split_group_aucprs")
r_rec_split_group_aucprs_avg

aucprs <- grabVals(aucprs, r_rec_split_group_aucprs)

p.values <- fishing(p.values, r_rec_split_group_aucprs)

saveRDS(r_rec_split_group_aucprs, file = "../Outputs/TEST OUTPUT FILE DELETE.RData")
rm(list=ls())

r_rec_split_group_aucprs <- readRDS(file = "../Outputs/TEST OUTPUT FILE DELETE.RData")


```






