---
title: "adj_cohort_split_group_tox_top02_chr"
author: "Noah Lepola"
date: "2024-11-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(randomForest)
library(ROCR)



```

```{r}
load(file = "age_dev")
load(file = "pt.char")
load(file = "pt.status")
```


Splitting by cohort and outcome
```{r}
train.outcomes <- filter(pt.status, Cohort == "Adj", 
Reason.for.discontinuation == "Therapy complete" |
  Reason.for.discontinuation == "Toxicity")
train.outcomes <- arrange(train.outcomes, desc(Sample))

test.outcomes <- filter(pt.status, Cohort == "Adj Validation",
Reason.for.discontinuation == "Therapy complete" |
  Reason.for.discontinuation == "Toxicity")
test.outcomes <- arrange(test.outcomes, desc(Sample))


train.seq <- filter(age_dev, (Sample %in% train.outcomes$Sample))
train.seq <- arrange(train.seq, desc(Sample))


test.seq <- filter(age_dev, (Sample %in% test.outcomes$Sample))
test.seq <- arrange(test.seq, desc(Sample))
```

NECTIN2, `KIR_Inhibiting_Subgroup_2`, CDKN1B, HAVCR2, B3GAT1, RUNX3, PDCD1LG2, `IL-10`, TBX21, `PTPRC_1`, CCR4, TNF, KLRG1, CXCR3, EOMES
top characteristics using only Adj (exploratory) cohort Therapy, `BMI (kg/m2)`, `Platelets (K/uL)`, `LDH (U/L)`, Stage, Age



Limiting information to just what is needed for this model and splitting outcome from expression
```{r}
train.seq <- train.seq %>% select(Sample, NECTIN2)
test.seq <- test.seq %>% select(Sample, NECTIN2)

top.c <- pt.char %>% select(Sample, Therapy, `BMI (kg/m2)`, `Platelets (K/uL)`,
                            `LDH (U/L)`, Stage)
train.seq <- left_join(train.seq, top.c)
test.seq <- left_join(test.seq, top.c)

train.outcomes <- train.outcomes %>% select(Sample, `Reason.for.discontinuation`)
test.outcomes <- test.outcomes %>% select(Sample, `Reason.for.discontinuation`)
```



```{r}
source("tox_functions.R")
```

```{r}
seed_list <- c(12345:12369)
```

```{r}
#Currently working on this
rf_tox_top_chr_aucprs <- kTest(seed_list) 
rf_tox_top_chr_aucprs_avg <- mean(rf_tox_top_chr_aucprs$AUCPR)
write.csv(rf_tox_top_chr_aucprs, file = "rf_tox_top_chr_aucprs.csv")
rf_tox_top_chr_aucprs_avg

```



```{r}
run_number <- 1:1000
seed_list_r <- c(12345:13344)
rf_ad_tox_top_char_random_1000 <- data.frame(run = run_number, Average = NA)
```

```{r}
for (j in 1:length(run_number)) {
  set.seed(seed_list_r[j])
train.outcomes$Reason.for.discontinuation<- 
  (sample(train.outcomes$Reason.for.discontinuation))

test.outcomes$Reason.for.discontinuation<- 
  (sample(test.outcomes$Reason.for.discontinuation))

r_random_tox_aucprs <- kTest(seed_list) 
avg <- mean(r_random_tox_aucprs$AUCPR)
rf_ad_tox_top_char_random_1000[j, 2] <- avg

  }
mean(rf_ad_tox_top_char_random_1000$Average)

write.csv(rf_ad_tox_top_char_random_1000, file = "rf_ad_tox_top_char_random_1000.csv")
```


