---
title: "random_sample_rf"
author: "Noah Lepola"
date: "2024-11-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(randomForest)
library(ROCR)



```

Loading file
```{r}
load(file = "../Outputs/gene.exp")
load(file = "../Outputs/pt.char")
load(file = "../Outputs/pt.status")
```


Splitting by cohort and outcome
```{r}
train.outcomes <- filter(pt.status, Cohort == "Adj", Reason.for.discontinuation 
  == "Therapy complete" | Reason.for.discontinuation == "Toxicity")

test.outcomes <- filter(pt.status, Cohort == "Adj Validation", 
  Reason.for.discontinuation == "Therapy complete" | Reason.for.discontinuation
  == "Toxicity")

train.seq <- filter(gene.exp, (Sample %in% train.outcomes$Sample))
test.seq <- filter(gene.exp, (Sample %in% test.outcomes$Sample))
```


Randomizing outcome
```{r}
train.outcomes$random.outcome<- (sample(train.outcomes$Reason.for.discontinuation))
test.outcomes$random.outcome<- (sample(test.outcomes$Reason.for.discontinuation))

```


```{r}
k_validate <- function(seed){
  set.seed(seed)
  

    out <- list()

      out[[1]] <- getROC(train.seq, train.outcomes, test.seq, test.outcomes)
      

  avg_aucpr <- lapply(out, function(x){ x[[1]]})
  message("\nAccuracy average: ", (rowMeans(as.data.frame(avg_aucpr))))
  return(out)
}
```

```{r}
# Function create and test RF model #
getROC <- function(train.seq, train.outcomes, test.seq, test.outcomes){
  model.training <- randomForest(x = train.seq[,-1, drop=FALSE], y = as.factor(train.outcomes$random.outcome))
  test.preds <- predict(model.training, test.seq[,-1, drop=FALSE])

#shuffling to make each run random  
train.outcomes$random.outcome<- (sample(train.outcomes$Reason.for.discontinuation))
test.outcomes$random.outcome<- (sample(test.outcomes$Reason.for.discontinuation))
print(test.outcomes[1, 4])
    
  # Prediction confusion matrix
  table(observed = test.outcomes$random.outcome, predicted = test.preds)
  
  prediction_for_roc_curve <- predict(model.training, test.seq[,-1, drop=FALSE],
                                      type="prob")
  
  pred <- prediction(prediction_for_roc_curve[,2], test.outcomes$random.outcome,
                     label.ordering = c("Therapy complete", "Toxicity"))
  
  perf <- performance(pred, "tpr", "fpr")
  
  aucpr_ROCR <- performance(pred, measure = "aucpr")
  # print(aucpr_ROCR)
  aucpr <- aucpr_ROCR@y.values[[1]]
  print(aucpr)
  
  df <- data.frame(FalsePositive=c(perf@x.values[[1]]),
                   TruePositive=c(perf@y.values[[1]]))
  out <- list(aucpr, df)
  
  return(out)
  
}

```

```{r}
# Grabbing AUROC values from input models #
grabVals <- function(input){
  out <- list()
    for(i in 1:length(seed_list)){
      out <- append(out, input[[i]][[1]][[1]])
    }
  out
}
```

```{r}
# Main function call to generate RF models using 25 seeds #
kTest <- function(seed_list){
  out <- list()
   for(i in 1:length(seed_list)){
    out[[i]] <- k_validate(seed = seed_list[i])

   }
  out <- grabVals(out)
  
  # CW edit to function 
  out <- do.call(rbind.data.frame, out)
  colnames(out) <- c("AUCPR")
  out
}
```

```{r}
seed_list <- c(12345:13344)
```

```{r}
#Currently working on this
r_random_tox_split_group_aucprs <- kTest(seed_list) 
r_random_tox_split_group_aucprs_avg <- mean(r_random_tox_split_group_aucprs$AUCPR)
#save(r_random_tox_split_group_aucprs, file = "../Outputs/r_random_tox_split_group_aucprs")
# r_random_tox_split_group_aucprs_avg
# range(r_random_tox_split_group_aucprs$AUCPR)
write.csv(r_random_tox_split_group_aucprs, 
          "../Outputs/r_random_tox_split_group_aucprs.csv")
```



