---
title: "adjing_cohort_split_group_rec"
author: "Noah Lepola"
date: "2024-11-025"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(randomForest)
library(ROCR)

```

Loading file
```{r}
load(file = "gene.exp")
load(file = "pt.char")
load(file = "pt.status")
```


Splitting by cohort and outcome
```{r}
sorting <- function(data, cohort, outcome1, outcome2){
  filter(data, 
         Cohort == cohort, 
         Reason.for.discontinuation == outcome1 | 
           Reason.for.discontinuation == outcome2)  
}
  
train.outcomes <- sorting(pt.status,
                          "Adj",
                          "Therapy complete", 
                          "Progression")

train.outcomes <- arrange(train.outcomes, desc(Sample))


test.outcomes <- sorting(pt.status, 
                        "Adj Validation",
                        "Therapy complete",
                        "Progression")

test.outcomes <- arrange(test.outcomes, desc(Sample))


train.seq <- filter(gene.exp, (Sample %in% train.outcomes$Sample))
train.seq <- arrange(train.seq, desc(Sample))


test.seq <- filter(gene.exp, (Sample %in% test.outcomes$Sample))
test.seq <- arrange(test.seq, desc(Sample))

```

```{r}
source("rec_functions.R")
```

```{r}
seed_list <- c(12345:12369)

```

```{r}
rf_rec_aucprs <- kTest(seed_list) 
rf_rec_aucprs_avg <- mean(rf_rec_aucprs$AUCPR)
write.csv(rf_rec_aucprs, file = "rf_rec_aucprs.csv")
rf_rec_aucprs_avg

```


```{r}
run_number <- 1:1000
seed_list_r <- c(12345:13344)
rf_rec_random_1000 <- data.frame(run = run_number, Average = NA)
```

```{r}
for (j in 1:length(run_number)) {
  set.seed(seed_list_r[j])
train.outcomes$Reason.for.discontinuation<- 
  (sample(train.outcomes$Reason.for.discontinuation))

test.outcomes$Reason.for.discontinuation<- 
  (sample(test.outcomes$Reason.for.discontinuation))

r_random_rec_split_group_aucprs <- kTest(seed_list) 
avg <- mean(r_random_rec_split_group_aucprs$AUCPR)
rf_rec_random_1000[j, 2] <- avg

  }
mean(rf_rec_random_1000$Average)

write.csv(rf_rec_random_1000, file = "rf_rec_random_1000.csv")
```
