---
title: "svm"
author: "Noah Lepola"
date: "2025-01-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(e1071)
library(caret)
library(PRROC)

```


Loading files
```{r}
load(file = "../Outputs/xgb.char")
load(file = "../Outputs/pt.status")
load(file = "../Outputs/gene.exp")
```

joining everything to run in svm
```{r}
status.char <- left_join(pt.status, xgb.char)
status.char.exp <- left_join(status.char, gene.exp)


```

splitting into testing and training for therapy complete or recurrence
Removing StageI because svm can't handle all 0
```{r}
train <- filter(status.char.exp,
                Cohort == "Adj", 
                Reason.for.discontinuation == "Therapy complete" | 
                  Reason.for.discontinuation == "Toxicity") %>%
  select(`Reason.for.discontinuation`, 
         TNF, TGFB1)
# `IL-10`, `KIR_Inhibiting_Subgroup_2`, `KIR_Activating_Subgroup_2`)

test <- filter(status.char.exp,
               Cohort == "Adj Validation", 
               Reason.for.discontinuation == "Therapy complete" | 
                 Reason.for.discontinuation == "Toxicity") %>% 
  select(`Reason.for.discontinuation`, 
  TNF, TGFB1)
# `IL-10`, `KIR_Inhibiting_Subgroup_2`, `KIR_Activating_Subgroup_2`)

```


Converting to factor for use in svm
```{r}
train$Reason.for.discontinuation <- as.factor(train$Reason.for.discontinuation)
test$Reason.for.discontinuation <- as.factor(test$Reason.for.discontinuation)

```


```{r}
set.seed(12345)
```


```{r}

train.model <- svm(`Reason.for.discontinuation` ~ .,
                   data = train, 
                   probability = TRUE, 
                   type = "C", 
                   # class.weights=c("Toxicity"=2.1,
                   #                 "Therapy complete"=0.65625)
                   )

test.model <- predict(train.model, 
                      test,
                      probability = TRUE,
                      type = "C",
                      # class.weights=c("Toxicity"=1.615385,
                      #                 "Therapy complete"=0.7241379)
                      )

test.model.df <- data.frame(test.model)



confusionMatrix(test$Reason.for.discontinuation, 
                test.model.df$test.model, 
                positive = "Toxicity")

```


Creating df for calculating aucpr
```{r}
test.store <- data.frame(attr(test.model, "probabilities"))

scores <- data.frame(test.store$Toxicity, test$Reason.for.discontinuation)

scores <- scores %>%
  mutate(score = case_when((test.Reason.for.discontinuation == "Therapy complete") ~ 0,
         TRUE ~ 1))
```


Calculating aucpr
```{r}
aucpr <- pr.curve(scores.class0=scores[scores$score=="1",]$test.store.Toxicity,
             scores.class1=scores[scores$score=="0",]$test.store.Toxicity,
             curve=T)

aucpr$auc.integral
```


Making a plot
```{r}
y <- as.data.frame(aucpr$curve)
ggplot(y, aes(V1, V2))+geom_path()+ylim(0,1)
```



