---
title: "adjing pub objects"
author: "Caroline Wheeler"
date: "2023-11-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)

# source("00-paths.R")
```

Publication objects = cleaned R objects in the repo, without PHI, that are the inputs to ALL of the figures

file path 
```{r}
paths.tdrive <- "/Volumes/spakowicz/"
#paths.tdrive <- "T:/Labs/Spakowicz/"
```

read in necessary data
```{r warning=FALSE}
# irAEs
irAE <- readxl::read_xlsx(file.path(paths.tdrive,"mitox/Clinical info/Mitoxstudy_patient_symptoms_AM_2.xlsx")) %>%
  dplyr::select(-`Patient Name`, - MRN)

# recist, CT scans
recist.scan <- readxl::read_xlsx(file.path(paths.tdrive, "mitox/Clinical info/OSU-19125_patient_progression_RECIST_KK_v4.xlsx")) %>%
  dplyr::select(-Name, -MRN)

# microbiome metadata
micSamp <- read.table(file.path(paths.tdrive, 'mitox/data/labii/mitox-samples-export_2022-10-21.tsv'), sep = '\t', header = TRUE, fill = NA)

# demographics
demo.dat <- read_excel(file.path(paths.tdrive, "mitox/Patient Logs/Demographics/Patient_demographics.xlsx")) %>%
   select(-MRN, -Name)

# PFS
pfs <- readxl::read_xlsx(file.path(paths.tdrive, "mitox/Clinical info/OSU-19125_patient_progression_RECIST_KK_v4.xlsx"),
                               sheet = "Progression dates")

# microbiome taxonomic data merged metaphlan output 
taxa <- read.csv("../../../data/mpa_aggregated_long_2023-10-26.csv")

# microbiome sample matching 
samps <- read_xlsx( file.path(paths$oneDrive, "/data/onecodex/2021-10-27_mitox_One Codex Sample Registration.xlsx"))
samps2 <- read_xlsx( file.path(paths$oneDrive, "/data/onecodex/2022-07-27_mitox_remaining_One Codex Sample Registration.xlsx")) %>%
   select(-`Specimen Type`)
samps <- rbind(samps, samps2) 

# blood data
blood.adj <- openxlsx::readWorkbook(xlsxFile =  file.path(paths.tdrive, "mitox/Clinical info/Patient Data 7-1-22.xlsm"), sheet = "Adj Datasheet", startRow = 2)
blood.met <- openxlsx::readWorkbook(xlsxFile =  file.path(paths.tdrive, "mitox/Clinical info/Patient Data 7-1-22.xlsm"), sheet = "Met Datasheet", startRow = 2)
blood.metj <- openxlsx::readWorkbook(xlsxFile =  file.path(paths.tdrive, "mitox/Clinical info/Patient Data 7-1-22.xlsm"), sheet = "Jason Met Cohort", startRow = 2)

# Patient log
pt_log <- readxl::read_xlsx(file.path(paths.tdrive,"mitox/Patient Logs/OSU 19125 Patient Log.xlsx"), skip = 3) %>%
  dplyr::select(-`Pt Name`, -MRN)

# Nanostring summary 
nano.adj <- readxl::read_xlsx(file.path(paths.tdrive, "mitox/data/Burd_clinicdata/Burd_NanostringSummary_June2022.xlsx"), sheet = 2)
nano.metdis <- readxl::read_xlsx(file.path(paths.tdrive, "mitox/data/Burd_clinicdata/Burd_NanostringSummary_June2022.xlsx"), sheet = 4)
nano.metval <- readxl::read_xlsx(file.path(paths.tdrive, "mitox/data/Burd_clinicdata/Burd_NanostringSummary_June2022.xlsx"), sheet = 5)
nano.metnivo <- readxl::read_xlsx(file.path(paths.tdrive, "mitox/data/Burd_clinicdata/Burd_NanostringSummary_June2022.xlsx"), sheet = 6)
```

Demographics (Input to Tables 1, S1)
Rows are pts
```{r}
# clean up demographic data
demographics <- demo.dat %>% 
  filter(!is.na(`Patient Id`)) %>%
  select(-c(No., Notes))

# get irAE, symptoms, response, pfs, microbiome sample presence
recist.mic <- recist.scan %>%
  select(`Patient ID`, RECIST, Category, Samples) %>%
  rename("Patient Id" = `Patient ID`,
         "Mic.Samp" = Samples) %>%
  filter(!is.na(`Patient Id`))

pfs <- pfs %>%
  select(`Patient Id`, `12-month PFS`)

irae <- irAE %>%
  dplyr::select(`Patient Id`, `Attribution (Final)`) %>%
  rename(irAE = `Attribution (Final)`) %>%
  filter(irAE == "Yes") %>%
  distinct()

# join 
demographics <- merge(demographics, recist.mic, all=T)
demographics <- merge(demographics, pfs, all=T)
demographics <- merge(demographics, irae, all=T)

# slight mutation to irae and MDSC
demographics <- demographics %>%
  mutate(irAE = case_when(is.na(irAE)~ "No", .default = irAE),
         `MDSC #` = case_when(`MDSC #` == "N/A"~NA, .default = `MDSC #`))

# filter to ADJ only
demographics <- demographics %>%
  filter(Cohort == "Adj")

save(demographics, file = "../data/clinical.rds")
```
