---
title: "tc vs tox demographics"
author: "Noah Lepola"
date: "2024-02-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(openxlsx)
library(broom)

```

```{r}
#creating data frame of just the nanostring data I need

#Reading in nanostring data file
nano.data <- readxl::read_xlsx("T:/Labs/Spakowicz/mitox/data/Burd_clinicdata/Burd_NanostringSummary_June2022.xlsx", sheet = 2) %>%
  drop_na(Sample)

#removing empty rows
sampledata <- nano.data %>%
  select(Sample, Age, `BMI (kg/m2)`,`Relative lymphocyte count (%)`, `Platelets (K/uL)`, `LDH (U/L)`, `Stage (7th ed.) prior to therapy`, Therapy)

#getting all names to the same format
sampledata$Sample <-gsub(" ", "-", sampledata$Sample)
```

```{r}
#Reading in patient data
adjing.data <- openxlsx::loadWorkbook("T:/Labs/Spakowicz/mitox/Clinical info/Patient Data 7-1-22.xlsm")


#selecting sheet with toxicity/treatment completed
Adj_Datasheet <- readWorkbook(adjing.data, sheet = "Adj Datasheet", startRow = 2)

alting_names <- rename(Adj_Datasheet, Coded.Sample = 52, Drugs = 21, Date.of.treatment = 22)

new_status <- subset(alting_names, Cohort != "Excluded")

#creating dataframes with only sample and tox
status <- new_status %>%
  select(`Coded.Sample.#`, `Reason.for.discontinuation`)

#adjusting names to match
status$`Coded.Sample.#` <- gsub( " *\\(.*?\\) *", "", status$`Coded.Sample.#`)
status$`Coded.Sample.#` <- gsub( " *\\(.*?\\)*", "", status$`Coded.Sample.#`)
status$`Coded.Sample.#` <-gsub("- ", "-", status$`Coded.Sample.#`)
status$`Coded.Sample.#` <-gsub("^\\s+|\\s+$", "", status$`Coded.Sample.#`)
#removing samples that aren't in nanostring
status2 <- subset(status, (`Coded.Sample.#` %in% sampledata$Sample)) 

```


```{r}
  #Getting toxicity
tox <- subset(status2, grepl(paste("Tox", collapse = "|"), Reason.for.discontinuation))
#removing extra information and correcting spelling
tox$Reason.for.discontinuation <- gsub( " */*Intolerance", "", tox$Reason.for.discontinuation)
tox$Reason.for.discontinuation <- gsub( " */ *", "", tox$Reason.for.discontinuation)
tox$Reason.for.discontinuation <- gsub( " *\\(.*?\\) *", "", tox$Reason.for.discontinuation)
tox$Reason.for.discontinuation <- gsub( " *\\(.*?\\)*", "", tox$Reason.for.discontinuation)
tox$Reason.for.discontinuation <-gsub("- ", "-", tox$Reason.for.discontinuation)
tox$Reason.for.discontinuation <-gsub("^\\s+|\\s+$", "", tox$Reason.for.discontinuation)
tox$Reason.for.discontinuation <-gsub("Toxcity", "Toxicity", tox$Reason.for.discontinuation)
    #Getting completed treatment
  complete_t <- subset(status2, grepl(paste("Therapy complete", collapse = "|"), Reason.for.discontinuation))
    
    
#merging into one file
tc.tox.outcomes <- rbind(tox, complete_t)
#keeping only sampledata with ct or tox
tc.tox.data <- subset(sampledata, (Sample %in% tc.tox.outcomes$`Coded.Sample.#`))
#renaming column and merging 
tc.tox.df <- left_join(tc.tox.outcomes, tc.tox.data, by = c("Coded.Sample.#" = "Sample" ))


#Adding just number for stage

IV <- c("IV")
IIIvalues <- c("IIIC", "IIIA", "IIIB", "III")
III <- paste(IIIvalues, collapse = "|")
IIvalues <- c("IIC", "IIB")
II <- paste(IIvalues, collapse = "|")
start.stage <- tc.tox.df$`Stage (7th ed.) prior to therapy`

tc.tox.df$Stage <- ifelse(grepl(III, start.stage), as.numeric("3"),
                          ifelse(grepl(IV, start.stage), as.numeric("4"),
                                ifelse(grepl(II, start.stage), as.numeric("2"), as.numeric("1"))))

#switching therapy to a number Nivolumab=1 Pembrolizumab=2 Ipilimumab=3

tc.tox.df$therapy.used <- ifelse(tc.tox.df$Therapy == 'Nivolumab', as.numeric("1"),
               ifelse(tc.tox.df$Therapy == 'Pembrolizumab', as.numeric("1"),
                 ifelse(tc.tox.df$Therapy == 'Ipilimumab', as.numeric("3"), as.numeric("0"))))



#removing columns I don't need now
tc.tox.df <- tc.tox.df %>%
  select(-`Stage (7th ed.) prior to therapy`) 

# Get a vector of column names
names <- colnames(tc.tox.df[, 3:9])
fixed.names <- make.names(colnames(tc.tox.df[, 3:9]))

#adding numbers for outcome
tc.tox.df <- tc.tox.df %>% mutate(Outcome = case_when(
  Reason.for.discontinuation == "Therapy complete" ~ 1,
  TRUE ~ 0))

#renaming columns to ones that don't produce an error
fixed.tc.tox.df <- tc.tox.df %>% 
  rename_with(~ fixed.names[which((names) == .x)], .cols = any_of(names))

#create dataframe to store the output 
logr_tox <- (data.frame(characteristic = names,
                   estimate = NA,
                   p.value = NA))

char.outcome <- fixed.tc.tox.df %>%
  select(-`Coded.Sample.#`, -Reason.for.discontinuation) 


```

```{r}

for (g in 1:length(fixed.names)) {
  f <- as.formula(paste0("Outcome ~ ",fixed.names[g]))
   tmp <- glm(formula = f, data = char.outcome, family = binomial)
   tmpdf <- broom::tidy(tmp)
#  retrieve the line of interest with g, estimate, and p-value
   logr_tox$estimate[g] <- tmpdf$estimate[2]
   logr_tox$p.value[g] <- tmpdf$p.value[2]
 
}
logr_tox <- logr_tox %>%
   mutate(FDR = p.adjust(p.value)) %>%
   arrange(FDR) 
#might have a - sign. WIll put to console, might want to assign it


tc_samples <- subset(fixed.tc.tox.df, (fixed.tc.tox.df$Outcome == 1))
tox_samples <- subset(fixed.tc.tox.df, (fixed.tc.tox.df$Outcome == 0))

#mean(tc_samples$BMI..kg.m2.)
#mean(tox_samples$BMI..kg.m2.)

```
