---
title: "Additional metrics script"
author: "Noah Lepola"
date: "2025-03-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(caret)
library(tidyverse)
library(ggplot2)

```

```{r}
source("../rf_functions.R")
```

Loading all the files needed. First in each section is the actual run data, second is the 1000x random shuffle runs
```{r}
# rf_rec <- readRDS(file = "../Outputs/rf_rec.RData")
# rf_rec_random_25000<- readRDS(file = "../Outputs/rf_rec_random_25000.RData")
# 
# rf_rec_top <- readRDS(file = "../Outputs/rf_rec_top.RData")
# rf_rec_top_random_25000<- readRDS(file = "../Outputs/rf_rec_top_random_25000.RData")
# 
# rf_rec_top_alt_top <- readRDS(file = "../Outputs/rf_rec_top_alt_top.RData")
# rf_rec_top_alt_top_random_25000<- readRDS(file = "../Outputs/rf_rec_top_alt_top_random_25000.RData")
# 
# rf_rec_top_xgboost <- readRDS(file = "../Outputs/rf_rec_top_xgboost.RData")
# rf_rec_top_xgboost_random_25000<- readRDS(file = "../Outputs/rf_rec_top_xgboost_random_25000.RData")
# 
# rf_rec_top_char <- readRDS(file = "../Outputs/rf_rec_top_char.RData")
# rf_rec_top_char_random_25000<- readRDS(file = "../Outputs/rf_rec_top_char_random_25000.RData")

# rf_rec_top_2_2 <- readRDS(file = "../Outputs/rf_rec_top_2_2.RData")
# rf_rec_top_random_2_2_25000<- readRDS(file = "../Outputs/rf_rec_top_random_2_2_25000.RData")

# rf_rec_top_2_1 <- readRDS(file = "../Outputs/rf_rec_top_2_1.RData")
# rf_rec_top_random_2_1_25000<- readRDS(file = "../Outputs/rf_rec_top_random_2_1_25000.RData")

# rf_rec_top_1_1 <- readRDS(file = "../Outputs/rf_rec_top_1_1.RData")
# rf_rec_top_random_1_1_25000<- readRDS(file = "../Outputs/rf_rec_top_random_1_1_25000.RData")

# rf_rec_top_4_0 <- readRDS(file = "../Outputs/rf_rec_top_4_0.RData")
# rf_rec_top_random_4_0_25000<- readRDS(file = "../Outputs/rf_rec_top_random_4_0_25000.RData")
# rf_rec_top_3_0 <- readRDS(file = "../Outputs/rf_rec_top_3_0.RData")
# rf_rec_top_random_3_0_25000<- readRDS(file = "../Outputs/rf_rec_top_random_3_0_25000.RData")
# rf_rec_top_2_0 <- readRDS(file = "../Outputs/rf_rec_top_2_0.RData")
# rf_rec_top_random_2_0_25000<- readRDS(file = "../Outputs/rf_rec_top_random_2_0_25000.RData")
# rf_rec_top_1_0 <- readRDS(file = "../Outputs/rf_rec_top_1_0.RData")
# rf_rec_top_random_1_0_25000<- readRDS(file = "../Outputs/rf_rec_top_random_1_0_25000.RData")

rf_met_rec_top_3_0 <- readRDS(file = "../Outputs/rf_met_rec_top_3_0.RData")
rf_met_rec_top_random_3_0_25000<- readRDS(file = "../Outputs/rf_met_rec_top_random_3_0_25000.RData")

rf_met_rec_noipi_top_3_0 <- readRDS(file = "../Outputs/rf_met_rec_noipi_top_3_0.RData")
rf_met_rec_noipi_top_random_3_0_25000<- readRDS(file = "../Outputs/rf_met_rec_noipi_top_random_3_0_25000.RData")





# rf_tox <- readRDS(file = "../Outputs/rf_tox.RData")
# rf_tox_random_25000<- readRDS(file = "../Outputs/rf_tox_random_25000.RData")
# 
# rf_tox_top <- readRDS(file = "../Outputs/rf_tox_top.RData")
# rf_tox_top_random_25000<- readRDS(file = "../Outputs/rf_tox_top_random_25000.RData")
# 
# rf_tox_top_alt_top <- readRDS(file = "../Outputs/rf_tox_top_alt_top.RData")
# rf_tox_top_alt_top_random_25000<- readRDS(file = "../Outputs/rf_tox_top_alt_top_random_25000.RData")
# 
# rf_tox_top_xgboost <- readRDS(file = "../Outputs/rf_tox_top_xgboost.RData")
# rf_tox_top_xgboost_random_25000<- readRDS(file = "../Outputs/rf_tox_top_xgboost_random_25000.RData")
# 
# rf_tox_top_char <- readRDS(file = "../Outputs/rf_tox_top_char.RData")
# rf_tox_top_char_random_25000<- readRDS(file = "../Outputs/rf_tox_top_char_random_25000.RData")

# rf_tox_top_2_2 <- readRDS(file = "../Outputs/rf_tox_top_2_2.RData")
# rf_tox_top_random_2_2_25000<- readRDS(file = "../Outputs/rf_tox_top_random_2_2_25000.RData")

# rf_tox_top_2_1 <- readRDS(file = "../Outputs/rf_tox_top_2_1.RData")
# rf_tox_top_random_2_1_25000<- readRDS(file = "../Outputs/rf_tox_top_random_2_1_25000.RData")

# rf_tox_top_1_1 <- readRDS(file = "../Outputs/rf_tox_top_1_1.RData")
# rf_tox_top_random_1_1_25000<- readRDS(file = "../Outputs/rf_tox_top_random_1_1_25000.RData")

# rf_tox_top_4_0 <- readRDS(file = "../Outputs/rf_tox_top_4_0.RData")
# rf_tox_top_random_4_0_25000<- readRDS(file = "../Outputs/rf_tox_top_random_4_0_25000.RData")
# rf_tox_top_3_0 <- readRDS(file = "../Outputs/rf_tox_top_3_0.RData")
# rf_tox_top_random_3_0_25000<- readRDS(file = "../Outputs/rf_tox_top_random_3_0_25000.RData")
# 
# 
# rf_tox_top_2_0 <- readRDS(file = "../Outputs/rf_tox_top_2_0.RData")
# rf_tox_top_random_2_0_25000<- readRDS(file = "../Outputs/rf_tox_top_random_2_0_25000.RData")
# rf_tox_top_1_0 <- readRDS(file = "../Outputs/rf_tox_top_1_0.RData")
# rf_tox_top_random_1_0_25000<- readRDS(file = "../Outputs/rf_tox_top_random_1_0_25000.RData")


rf_met_tox_top_2_0 <- readRDS(file = "../Outputs/rf_met_tox_top_2_0.RData")
rf_met_tox_top_random_2_0_25000<- readRDS(file = "../Outputs/rf_met_tox_top_random_2_0_25000.RData")

rf_met_tox_noipi_top_2_0 <- readRDS(file = "../Outputs/rf_tox_noipi_top_2_0.RData")
rf_met_tox_noipi_top_random_2_0_25000<- readRDS(file = "../Outputs/rf_tox_noipi_top_random_2_0_25000.RData")


```


Loading files for no ipi runs
```{r}

rf_rec_noipi <- readRDS(file = "../Outputs/rf_rec.RData")
rf_rec_noipi_random_25000 <- readRDS(file = "../Outputs/rf_rec_noipi_random_25000.RData")

rf_rec_top_2_noipi <- readRDS(file = "../Outputs/rf_rec_top_2_noipi.RData")
rf_rec_top_random_2_noipi_25000 <- readRDS(file = "../Outputs/rf_rec_top_random_2_noipi_25000.RData")

rf_met_rec_noipi_top_2_0 <- readRDS(file = "../Outputs/rf_rec_top_2_noipi.RData")
rf_met_rec_noipi_top_random_2_0_25000 <- readRDS(file = "../Outputs/rf_met_rec_noipi_top_random_2_0_25000.RData")




rf_tox_noipi <- readRDS(file = "../Outputs/rf_tox.RData")
rf_tox_noipi_random_25000 <- readRDS(file = "../Outputs/rf_tox_noipi_random_25000.RData")

rf_tox_top_noipi_5 <- readRDS(file = "../Outputs/rf_tox_top_noipi_5.RData")
rf_tox_top_noipi_random_5_25000 <- readRDS(file = "../Outputs/rf_tox_top_noipi_random_5_25000.RData")

rf_met_tox_noipi_top_5_0 <- readRDS(file = "../Outputs/rf_met_tox_noipi_top_5_0.RData")
rf_met_tox_noipi_top_random_5_0_25000 <- readRDS(file = "../Outputs/rf_met_tox_noipi_top_random_5_0_25000.RData")

```


Creating a function to get the average from each run of the 1000x random and then calculate the percentile of the normal run
```{r}
met.p.calc <- function(randomdata, pos.outcome, output, dataobject){
#function that generates averages of metrics for randomized run
  random_met <- add.metrics(randomdata,
                            random_met,
                            pos.outcome)
  

#storing experimental run additional metrics   
    temp_conmat2 <- data.frame(run = 1:25,
                               Accuracy = NA,
                               Specificity = NA,
                               Precision = NA,
                               Recall = NA,
                               F1 = NA)
    
#generating additional metrics for experimental run    
  for (i in 1:25) {
    temp_conmat <- confusionMatrix(dataobject[[i]][[1]][[3]],
                                   positive = pos.outcome)
    
    temp_conmat2$Accuracy[i] <- temp_conmat[[3]][1]
    
    temp_conmat2$Specificity[i] <- temp_conmat[[4]][2]
    
    temp_conmat2$Precision[i] <- temp_conmat[[4]][5]
    
    temp_conmat2$Recall[i] <- temp_conmat[[4]][6]
    
    temp_conmat2$F1[i] <- temp_conmat[[4]][7]
    
  }
#storing percentiles    
    output <- data.frame(Accuracy = NA,
                         Specificity = NA,
                         Precision = NA,
                         Recall = NA,
                         F1 = NA)
    
#converting NAs to 0 so we don't skew the averages    
      # temp_conmat2[is.na(temp_conmat2)] <- 0
      
#percentile calculation for various metrics  
      
avg.acc <- mean(temp_conmat2$Accuracy)
output$Accuracy[1] <- p.calc(avg.acc,
                             random_met$Avg.Accuracy)

avg.s <- mean(temp_conmat2$Specificity)
output$Specificity[1] <- p.calc(avg.s,
                                random_met$Avg.Specificity)

avg.prec <- mean(temp_conmat2$Precision)
output$Precision[1] <- p.calc(avg.prec,
                              random_met$Avg.Precision)

avg.recall <- mean(temp_conmat2$Recall)
output$Recall[1] <- p.calc(avg.recall,
                           random_met$Avg.Recall)

avg.F1 <- mean(temp_conmat2$F1)
output$F1[1] <- p.calc(avg.F1,
                       random_met$Avg.F1)

data_wide <- full_join(random_met, temp_conmat2)
data_wide <- select(data_wide, -run)
data_graph <- data_wide %>% 
  gather(key="RunVersion", value="Val") %>%
  ggplot( aes(x=RunVersion, y=Val, fill=RunVersion)) +
    geom_violin()

print(data_graph)

output
}
```


```{r}
rec_noipi_perc <- met.p.calc(rf_rec_noipi_random_25000, "Progression", rec_noipi_perc, rf_rec_noipi)
rec_2_noipi_perc <- met.p.calc(rf_rec_top_random_2_noipi_25000, "Progression", rec_2_noipi_perc, rf_rec_top_2_noipi)
rec_met_2_noipi_perc <- met.p.calc(rf_met_rec_noipi_top_random_2_0_25000, "Progression", rec_met_2_noipi_perc, rf_met_rec_noipi_top_2_0)

tox_noipi_perc <- met.p.calc(rf_tox_noipi_random_25000, "Toxicity", tox_noipi_perc, rf_tox_noipi)
tox_5_noipi_perc <- met.p.calc(rf_tox_top_noipi_random_5_25000, "Toxicity", tox_5_noipi_perc, rf_tox_top_noipi_5)
tox_met_5_noipi_perc <- met.p.calc(rf_met_tox_noipi_top_random_5_0_25000, "Toxicity", tox_met_5_noipi_perc, rf_met_tox_noipi_top_5_0)

f1.rec <- c("Full panel", "CD160-VTCN1", "Metastatic")
f1.tox <- c("Full panel", "TNFRSF18-VTCN1-CCR4-AHR-TIGIT", "Metastatic")

f1.tox.df <- data.frame(Model = f1.tox,
                            "Average F1 Percentile" = NA)
f1.tox.df$Average.F1.Percentile[1] <- tox_noipi_perc$F1
f1.tox.df$Average.F1.Percentile[2] <- tox_5_noipi_perc$F1
f1.tox.df$Average.F1.Percentile[3] <- tox_met_5_noipi_perc$F1


f1.rec.df <- data.frame(Model = f1.rec,
                            "Average F1 Percentile" = NA)
f1.rec.df$Average.F1.Percentile[1] <- rec_noipi_perc$F1
f1.rec.df$Average.F1.Percentile[2] <- rec_2_noipi_perc$F1
f1.rec.df$Average.F1.Percentile[3] <- rec_met_2_noipi_perc$F1

```

```{r}
rec_order <- c("Full panel", "CD160-VTCN1", "Metastatic")

# Apply the custom order to the 'category' factor
f1.rec.df$Model <- factor(f1.rec.df$Model, levels = rec_order)


rec_plot <-ggplot(data = f1.rec.df, mapping=aes(x = Model, y = Average.F1.Percentile, fill = Average.F1.Percentile))+
    geom_bar(stat = "identity") +
    ylab("F1 Percentile")
   
#x = reorder(genes, Avg.AUCPR) 
# ggplot(df,aes(x,y,fill=y))+geom_bar(stat="identity")+scale_fill_gradient(low="blue",high="red")
print(rec_plot)
# ggsave("../figures/responsemodelperformance.png", height = 4, width = 7)

```


```{r}
tox_order <- c("Full panel", "TNFRSF18-VTCN1-CCR4-AHR-TIGIT", "Metastatic")

# Apply the custom order to the 'category' factor
f1.tox.df$Model <- factor(f1.tox.df$Model, levels = tox_order)



tox_plot <-ggplot(data = f1.tox.df, mapping=aes(x = Model, y = Average.F1.Percentile, fill = Average.F1.Percentile))+
    geom_bar(stat = "identity") +
    ylab("F1 Percentile")
   
#x = reorder(genes, Avg.AUCPR) 
# ggplot(df,aes(x,y,fill=y))+geom_bar(stat="identity")+scale_fill_gradient(low="blue",high="red")
print(tox_plot)
# ggsave("../figures/responsemodelperformance.png", height = 4, width = 7)

```



```{r}
random_met <- add.metrics(rf_rec_noipi_random_25000,
                          random_met,
                          "Progression")

    temp_conmat2 <- data.frame(run = 1:25,
                             Accuracy = NA,
                             Specificity = NA,
                             Precision = NA,
                             Recall = NA,
                             F1 = NA)


  for (i in 1:25) {
  temp_conmat <- confusionMatrix(rf_rec_noipi_random_25000[[i]][[1]][[3]],
                                 positive = "Progression")

  temp_conmat2$Accuracy[i] <- temp_conmat[[3]][1]

  temp_conmat2$Specificity[i] <- temp_conmat[[4]][2]

  temp_conmat2$Precision[i] <- temp_conmat[[4]][5]

  temp_conmat2$Recall[i] <- temp_conmat[[4]][6]

  temp_conmat2$F1[i] <- temp_conmat[[4]][7]

}
print(mean(temp_conmat2$F1))

cat(random_met$Avg.F1, sep = "\n")
cat(temp_conmat2$F1, sep = "\n")
avg.met.F1<- mean(temp_conmat2$F1)

percentile <- p.calc(avg.met.F1, random_met$Avg.F1)

```


```{r}
rec_random <- add.metrics(rf_rec_noipi_random_25000,
                          random,
                          "Progression")

    rec <- data.frame(run = 1:25,
                             Accuracy = NA,
                             Specificity = NA,
                             Precision = NA,
                             Recall = NA,
                             F1 = NA)


  for (i in 1:25) {
  temp_conmat <- confusionMatrix(rf_rec_noipi[[i]][[1]][[3]],
                                 positive = "Progression")

  rec$Accuracy[i] <- temp_conmat[[3]][1]

  rec$Specificity[i] <- temp_conmat[[4]][2]

  rec$Precision[i] <- temp_conmat[[4]][5]

  rec$Recall[i] <- temp_conmat[[4]][6]

  rec$F1[i] <- temp_conmat[[4]][7]

  }

rec.avg.F1<- mean(rec$F1)

rec_random_plot <- ggplot(data = rec_random, aes(x = Avg.F1)) + 
  geom_histogram(bins = 100) +
  geom_vline(xintercept = rec.avg.F1, color = "red")

print(rec_random_plot)
        
# cat(random$Avg.F1, sep = "\n")
# cat(temp_conmat2$F1, sep = "\n")
# avg.F1<- mean(temp_conmat2$F1)
# 
# percentile <- p.calc(avg.F1, random$Avg.F1)
```



```{r}
rec_2_random <- add.metrics(rf_rec_top_random_2_noipi_25000,
                          random,
                          "Progression")

    rec2 <- data.frame(run = 1:25,
                             Accuracy = NA,
                             Specificity = NA,
                             Precision = NA,
                             Recall = NA,
                             F1 = NA)


  for (i in 1:25) {
  temp_conmat <- confusionMatrix(rf_rec_top_2_noipi[[i]][[1]][[3]],
                                 positive = "Progression")

  rec2$Accuracy[i] <- temp_conmat[[3]][1]

  rec2$Specificity[i] <- temp_conmat[[4]][2]

  rec2$Precision[i] <- temp_conmat[[4]][5]

  rec2$Recall[i] <- temp_conmat[[4]][6]

  rec2$F1[i] <- temp_conmat[[4]][7]

  }

rec2.avg.F1<- mean(rec2$F1)

rec_2_random_plot <- ggplot(data = rec_2_random, aes(x = Avg.F1)) + 
  geom_histogram(bins = 100) +
  geom_vline(xintercept = rec2.avg.F1, color = "red")

print(rec_2_random_plot)
        
# cat(random$Avg.F1, sep = "\n")
# cat(temp_conmat2$F1, sep = "\n")
# avg.F1<- mean(temp_conmat2$F1)
# 
# percentile <- p.calc(avg.F1, random$Avg.F1)
```




```{r}

tox_order <- c("Full panel", "TNFRSF18-VTCN1-CCR4-AHR-TIGIT", "Metastatic")

# Apply the custom order to the 'category' factor
f1.tox.df$Model <- factor(f1.tox.df$Model, levels = tox_order)



tox_plot <-ggplot(data = f1.tox.df, mapping=aes(x = Model, y = Average.F1.Percentile, fill = Average.F1.Percentile))+
    geom_bar(stat = "identity") +
    ylab("F1 Percentile")



```



```{r}
# test1 <- add.metrics(rf_rec_random_25000, test1, "Progression")
# rec_met_perc <- met.p.calc(rf_rec_random_25000, "Progression", rec_met_perc, rf_rec)
# rec_top_met_perc <- met.p.calc(rf_rec_top_random_25000, "Progression", rec_top_met_perc, rf_rec_top)
# rec_alt_met_perc <- met.p.calc(rf_rec_top_alt_top_random_25000, "Progression", rec_alt_met_perc, rf_rec_top_alt_top)
# rec_xgb_met_perc <- met.p.calc(rf_rec_top_xgboost_random_25000, "Progression", rec_xgb_met_perc, rf_rec_top_xgboost)
# rec_top_char_perc <- met.p.calc(rf_rec_top_char_random_25000, "Progression", rec_top_char_perc, rf_rec_top_char)

# rec_2_2_met_perc <- met.p.calc(rf_rec_top_random_2_2_25000, "Progression", rec_alt_met_perc, rf_rec_top_2_2)
# rec_2_1_met_perc <- met.p.calc(rf_rec_top_random_2_1_25000, "Progression", rec_alt_met_perc, rf_rec_top_2_1)
# rec_1_1_met_perc <- met.p.calc(rf_rec_top_random_1_1_25000, "Progression", rec_alt_met_perc, rf_rec_top_1_1)

# rec_4_0_met_perc <- met.p.calc(rf_rec_top_random_4_0_25000, "Progression", rec_alt_met_perc, rf_rec_top_4_0)
# rec_3_0_met_perc <- met.p.calc(rf_rec_top_random_3_0_25000, "Progression", rec_alt_met_perc, rf_rec_top_3_0)
# rec_2_0_met_perc <- met.p.calc(rf_rec_top_random_2_0_25000, "Progression", rec_alt_met_perc, rf_rec_top_2_0)
# rec_1_0_met_perc <- met.p.calc(rf_rec_top_random_1_0_25000, "Progression", rec_alt_met_perc, rf_rec_top_1_0)

rec_met_3_0_met_perc <- met.p.calc(rf_met_rec_top_random_3_0_25000, "Progression", rec_alt_met_perc, rf_met_rec_top_3_0)

rec_met_noipi_3_0_met_perc <- met.p.calc(rf_met_rec_noipi_top_random_3_0_25000, "Progression", rec_alt_met_perc, rf_met_rec_noipi_top_3_0)



# tox_met_perc <- met.p.calc(rf_tox_random_25000, "Toxicity", tox_met_perc, rf_tox)
# tox_top_met_perc <- met.p.calc(rf_tox_top_random_25000, "Toxicity", tox_top_met_perc, rf_tox_top)
# tox_alt_met_perc <- met.p.calc(rf_tox_top_alt_top_random_25000, "Toxicity", tox_alt_met_perc, rf_tox_top_alt_top)
# tox_xgb_met_perc <- met.p.calc(rf_tox_top_xgboost_random_25000, "Toxicity", tox_xgb_met_perc, rf_tox_top_xgboost)
# tox_top_char_perc <- met.p.calc(rf_tox_top_char_random_25000, "Toxicity", tox_top_char_perc, rf_tox_top_char)

# tox_2_2_met_perc <- met.p.calc(rf_tox_top_random_2_2_25000, "Toxicity", tox_alt_met_perc, rf_tox_top_2_2)
# tox_2_1_met_perc <- met.p.calc(rf_tox_top_random_2_1_25000, "Toxicity", tox_alt_met_perc, rf_tox_top_2_1)
# tox_1_1_met_perc <- met.p.calc(rf_tox_top_random_1_1_25000, "Toxicity", tox_alt_met_perc, rf_tox_top_1_1)

# tox_4_0_met_perc <- met.p.calc(rf_tox_top_random_4_0_25000, "Toxicity", tox_alt_met_perc, rf_tox_top_4_0)
# tox_3_0_met_perc <- met.p.calc(rf_tox_top_random_3_0_25000, "Toxicity", tox_alt_met_perc, rf_tox_top_3_0)
# tox_2_0_met_perc <- met.p.calc(rf_tox_top_random_2_0_25000, "Toxicity", tox_alt_met_perc, rf_tox_top_2_0)
# tox_1_0_met_perc <- met.p.calc(rf_tox_top_random_1_0_25000, "Toxicity", tox_alt_met_perc, rf_tox_top_1_0)

tox_met_2_0_met_perc <- met.p.calc(rf_met_tox_top_random_2_0_25000, "Toxicity", tox_alt_met_perc, rf_met_tox_top_2_0)

tox_met_noipi_2_0_met_perc <- met.p.calc(rf_met_tox_noipi_top_random_2_0_25000, "Toxicity", tox_alt_met_perc, rf_met_tox_noipi_top_2_0)


```



```{r}

#   random_tox <- add.metrics(rf_tox_top_random_1_1_25000,
#                             random_rec,
#                             "Toxicity")
# 
# cat(random_tox$Avg.F1, sep = "\n")

hist(random_met$Avg.F1)
abline(v = mean(random_met$Avg.F1), col='red', lwd = 3)
```

