---
title: "auto f1 opt"
author: "Noah Lepola"
date: "2025-03-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(randomForest)
library(ROCR)
library(dplyr)
library(caret)

```

Loading file
```{r}

met_outcomes <-  readRDS(file = "../Outputs/met_cohort_outcomes.RData")
met_data <-  readRDS(file = "../Outputs/met_cohort_data.RData")
load(file = "../Outputs/logr_tox_metastatic.Rdata")
load(file = "../Outputs/logr_pro_metastatic.Rdata")
source("../rf_functions.R")



# load(file = "../Outputs/logr_pro_noipi_no_ipi")
# load(file = "../Outputs/logr_tox_noipi_no_ipi")
# load(file = "../Outputs/rec_split_chr_adj_no_ipi")
# load(file = "../Outputs/tox_split_chr_adj_no_ipi")
# load(file = "../Outputs/logr_pro_noipi")
# load(file = "../Outputs/logr_tox_noipi")
# load(file = "../Outputs/pt.status")
# load(file = "../Outputs/rec_split_chr_adj")
# load(file = "../Outputs/tox_split_chr_adj")

```

```{r}
seed_list <- c(12345:12369)
```






#note this section is for metastatic progression
```{r}
train.outcomes <- sorting(met_outcomes,
                          "Met Discovery",
                          "Therapy complete",
                          "Progression")

train.outcomes <- arrange(train.outcomes, desc(Sample))


test.outcomes <- sorting(met_outcomes,
                        "Met Validation",
                        "Therapy complete",
                        "Progression")

test.outcomes <- arrange(test.outcomes, desc(Sample))


train.seq <- filter(met_data,
                    (Sample %in% train.outcomes$Sample))
train.seq <- arrange(train.seq, desc(Sample))


test.seq <- filter(met_data,
                   (Sample %in% test.outcomes$Sample))
test.seq <- arrange(test.seq, desc(Sample))

ordered_pro <- logr_pro_metastatic$gene[order(logr_pro_metastatic$p.value)]

pro_list <- c("Sample", ordered_pro)

train.seq <- train.seq %>% select(all_of(pro_list))
test.seq <- test.seq %>% select(all_of(pro_list))



# top.c <- pt.char %>% select(Sample, Therapy, `BMI (kg/m2)`, `Platelets (K/uL)`,
#                             `LDH (U/L)`, Stage, Age)
# train.seq <- left_join(train.seq, top.c)
# test.seq <- left_join(test.seq, top.c)


```

#pro F1 auto opt
```{r}
opt_meta_pro <- data.frame(genes = 79:1, Avg.F1 = NA)

for (i in 1:79) {
rf_pro_top_char <- kTest(seed_list, "Therapy complete", "Progression", "Opt") 

    temp_conmat2 <- data.frame(run = 1:25,
                             F1 = NA)

  for (j in 1:25) {
    temp_conmat <- confusionMatrix(rf_pro_top_char[[j]][[1]][[3]],
                                   positive = "Progression")
    temp_conmat2$F1[j] <- temp_conmat[[4]][7]
    
  }
avg <- mean(temp_conmat2$F1)


opt_meta_pro$Avg.F1[i] <- avg
x = length(train.seq)
train.seq <- train.seq[-x]
test.seq <- test.seq[-x]

Sys.sleep(1)
}

save(opt_meta_pro, file = "../Outputs/opt_meta_pro.Rdata")

prometa_bestmodel_list <- ordered_pro[1:41]

save(prometa_bestmodel_list, file = "../Outputs/prometa_bestmodel_list.Rdata")


```


#pro graph
```{r}

load(file = "../Outputs/opt_meta_pro.Rdata")

ten_pro <- opt_meta_pro %>%
  filter(genes <=10)

pro_gene_number <- 1:nrow(ten_pro)

f1_plot <-ggplot(data = ten_pro, mapping=aes(x = -genes, y = Avg.F1, fill = Avg.F1))+
    scale_y_continuous(limits = c(0, 1)) +
    scale_x_continuous(n.breaks=10, labels = abs) +
    geom_bar(stat = "identity") +
    scale_fill_viridis_c(option = "magma", direction = -1) +
    coord_flip() +
    xlab("Number of Genes") +
    ylab("Progression Model Performance (Avg F1)") +
  theme_minimal() +
  theme(
    axis.title.x = element_text(size = 24, face = "bold", margin = ggplot2::margin(t = 10)),
    axis.title.y = element_text(size = 24, face = "bold", margin = ggplot2::margin(r = 10)),
    axis.text = element_text(size = 20),  
    legend.title = element_text(size=20), 
    legend.text = element_text(size=15)
    # plot.title = element_text(size = 18, face = "bold")
  )  

   

# ggplot(df,aes(x,y,fill=y))+geom_bar(stat="identity")+scale_fill_gradient(low="blue",high="red")
print(f1_plot)

```


#note this section is for tox no ipi
```{r}
train.outcomes <- sorting(met_outcomes,
                          "Met Discovery",
                          "Therapy complete",
                          "Toxicity")

train.outcomes <- arrange(train.outcomes, desc(Sample))


test.outcomes <- sorting(met_outcomes,
                        "Met Validation",
                        "Therapy complete",
                        "Toxicity")

test.outcomes <- arrange(test.outcomes, desc(Sample))


train.seq <- filter(met_data,
                    (Sample %in% train.outcomes$Sample))
train.seq <- arrange(train.seq, desc(Sample))


test.seq <- filter(met_data,
                   (Sample %in% test.outcomes$Sample))
test.seq <- arrange(test.seq, desc(Sample))

ordered_tox <- logr_tox_metastatic$gene[order(logr_tox_metastatic$p.value)]

tox_list <- c("Sample", ordered_tox)

train.seq <- train.seq %>% select(all_of(tox_list))
test.seq <- test.seq %>% select(all_of(tox_list))





# top.c <- pt.char %>% select(Sample, Therapy, `BMI (kg/m2)`, `Platelets (K/uL)`,
#                             `LDH (U/L)`, Stage, Age)
# train.seq <- left_join(train.seq, top.c)
# test.seq <- left_join(test.seq, top.c)


```


#tox F1 auto opt 
```{r}

opt_meta_tox <- data.frame(genes = 79:1, Avg.F1 = NA)

for (i in 1:79) {
rf_tox_top_char <- kTest(seed_list, "Therapy complete", "Toxicity", "Opt") 

    temp_conmat2 <- data.frame(run = 1:25,
                             F1 = NA)

  for (j in 1:25) {
    temp_conmat <- confusionMatrix(rf_tox_top_char[[j]][[1]][[3]],
                                   positive = "Toxicity")
    temp_conmat2$F1[j] <- temp_conmat[[4]][7]
    
  }
avg <- mean(temp_conmat2$F1)

opt_meta_tox$Avg.F1[i] <- avg
x = length(train.seq)
train.seq <- train.seq[-x]
test.seq <- test.seq[-x]

print(i)
print(avg)

Sys.sleep(1)
}

save(opt_meta_tox, file = "../Outputs/opt_meta_tox.Rdata")

toxmeta_bestmodel_list <- ordered_tox[1:5]

save(toxmeta_bestmodel_list, file = "../Outputs/toxmeta_bestmodel_list.Rdata")


```


#tox graph
```{r}

load(file = "../Outputs/opt_meta_tox.Rdata")

ten_tox <- opt_meta_tox %>%
  filter(genes <=10)

f1_plot <-ggplot(data = ten_tox, mapping=aes(x = -genes, y = Avg.F1, fill = Avg.F1))+
    scale_y_continuous(limits = c(0, 1)) +
    scale_x_continuous(n.breaks=10, labels = abs) +
    geom_bar(stat = "identity") +
    scale_fill_viridis_c(option = "magma", direction = -1) +
    coord_flip() +
    xlab("Number of Genes") +
    ylab("Toxicity Model Performance (Avg F1)") +
  theme_minimal() +
  theme(
    axis.title.x = element_text(size = 24, face = "bold", margin = ggplot2::margin(t = 10)),
    axis.title.y = element_text(size = 24, face = "bold", margin = ggplot2::margin(r = 10)),
    axis.text = element_text(size = 20),  
    legend.title = element_text(size=20), 
    legend.text = element_text(size=15)
    # plot.title = element_text(size = 18, face = "bold")
  )  
  
   
#x = reorder(genes, Avg.f1) 
# ggplot(df,aes(x,y,fill=y))+geom_bar(stat="identity")+scale_fill_gradient(low="blue",high="red")
print(f1_plot)
# ggsave("../figures/responsemodelperformance.png", height = 4, width = 7)

```
