---
title: "rec_importance"
author: "Noah Lepola"
date: "2025-02-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(randomForest)
library(ROCR)
```

Loading file
```{r}

load(file = "../Outputs/gene.exp")
load(file = "../Outputs/pt.char")
load(file = "../Outputs/pt.status")
```
Splitting by cohort and outcome

```{r}
source("../rf_functions.R")
```

Splitting the cohorts into the 
```{r}
train.outcomes <- sorting(pt.status,
                          "Adj",
                          "Therapy complete", 
                          "Progression")

train.outcomes <- arrange(train.outcomes, desc(Sample))


test.outcomes <- sorting(pt.status, 
                        "Adj Validation",
                        "Therapy complete",
                        "Progression") 

test.outcomes <- arrange(test.outcomes, desc(Sample))


train.seq <- filter(gene.exp,
                    (Sample %in% train.outcomes$Sample))
train.seq <- arrange(train.seq, desc(Sample))


test.seq <- filter(gene.exp,
                   (Sample %in% test.outcomes$Sample))
test.seq <- arrange(test.seq, desc(Sample))


```

```{r}
train.outcomes <-
  train.outcomes %>%
  select(Sample,
         `Reason.for.discontinuation`)


test.outcomes <-
  test.outcomes %>%
  select(Sample,
         `Reason.for.discontinuation`)
```


```{r}
seed_list <- c(12345:12369)
```

```{r}
k_validate <- function(seed, neg.outcome, pos.outcome){
  set.seed(seed)
  
  
  out <- list()
  
  out[[1]] <- getROC(train.seq, train.outcomes, test.seq, test.outcomes, neg.outcome, pos.outcome)
  
  
  avg_AUCPR <- lapply(out, function(x){ x[[1]]})
  message("\nAccuracy average: ", (rowMeans(as.data.frame(avg_AUCPR))))
  return(out)
}
```


```{r}
# Function create and test RF model #
getROC <- function(train.seq, train.outcomes, test.seq, test.outcomes, neg.outcome, pos.outcome){
  if(all(train.seq$Sample == train.outcomes$Sample) == FALSE){
    stop("Training Sample_IDs do not match")
  }
  if(all(test.seq$Sample == test.outcomes$Sample) == FALSE){
    stop("Testing Sample_IDs do not match")
  }
  model.training <- randomForest(x = train.seq[,-1, drop=FALSE], y = 
                          as.factor(train.outcomes$Reason.for.discontinuation), importance=TRUE)
  
  test.preds <- predict(model.training, 
                        test.seq[,-1, drop=FALSE])
  
  # Check variable importance
  varImpPlot(model.training)
  
  # Prediction confusion matrix
  pred_cm <- table(observed = test.outcomes$Reason.for.discontinuation,
                   predicted = test.preds)
  
  print(pred_cm)
  
  
  prediction_for_roc_curve <- predict(model.training, 
                                      test.seq[,-1, drop=FALSE],
                                      type="prob")
  
  pred <- prediction(prediction_for_roc_curve[,2], 
                     test.outcomes$Reason.for.discontinuation, 
                     label.ordering = 
                       c(neg.outcome, pos.outcome))
  #for making aucpr curves
  # scores <- data.frame(prediction_for_roc_curve[,2], test.outcomes$Reason.for.discontinuation)
  # 
  # scores <- scores %>%
  #   mutate(score = case_when((test.outcomes.Reason.for.discontinuation == "Therapy complete") ~ 1,
  #                            TRUE ~ 0))
  # print(prediction_for_roc_curve[,2])
  # aucpr <- pr.curve(scores.class0=scores[scores$score=="0",]$`prediction_for_roc_curve...2.`,
  #                   scores.class1=scores[scores$score=="1",]$`prediction_for_roc_curve...2.`,
  #                   curve=T)
  # 
  # y <- as.data.frame(aucpr$curve)
  # print(ggplot(y, aes(V1, V2))+geom_path()+ylim(0,1))
  
  perf <- performance(pred, "tpr", "fpr")
  
  AUCPR_ROCR <- performance(pred, measure = "aucpr")
  print(AUCPR_ROCR)
  AUCPR <- AUCPR_ROCR@y.values[[1]]
  print(AUCPR)
  
  df <- data.frame(FalsePositive=c(perf@x.values[[1]]),
                   TruePositive=c(perf@y.values[[1]]))
  
  varimp <- model.training$importance
  out <- list(AUCPR, df, pred_cm, varimp)
  
  return(out)
}
```


```{r}
# Grabbing AUROC values from input models #
grabVals <- function(output, input, seed_list){
  datalist <- list()
  
  for(i in 1:length(seed_list)){
    tempdata <- data.frame(as.list(input[[i]][[1]][[4]][,4]))
    datalist[[i]] <- tempdata
  }
  output <- do.call(rbind, datalist)

  output
}
```


```{r}
# Main function call to generate RF models using 25 seeds #
kTest <- function(seed_list, neg.outcome, pos.outcome){
  out <- list()
  for(i in 1:length(seed_list)){
    out[[i]] <- k_validate(seed = seed_list[i], neg.outcome, pos.outcome)
  }
  # out <- grabVals(out)
  # CW edit to function
  # out <- do.call(rbind.data.frame, out)
  # colnames(out) <- c("AUCPR")
  out
}
```


```{r}
rf_rec <- kTest(seed_list, "Therapy complete", "Progression") 

varimp <- train.seq[0,2:80]

varimp <- grabVals(varimp, rf_rec, seed_list)

rec.imp.w <- data.frame(as.list(apply(varimp, 2, median)))

rec.imp.l <- rec.imp.w %>% 
  pivot_longer(cols = 1:length(rec.imp.w), names_to = "Gene", values_to = "GINI") 
  
rec.imp.l  <- arrange(rec.imp.l, desc(GINI))

# saveRDS(rf_rec, file = "../Outputs/rf_rec.RData")



```


