---
title: "aucpr_and_cfm_template"
author: "Noah Lepola"
date: "2025-02-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(randomForest)
library(ROCR)
library(caret)


```

Loading file
```{r}

load(file = "../Outputs/gene.exp")
load(file = "../Outputs/pt.char")
load(file = "../Outputs/pt.status")
```
Splitting by cohort and outcome

```{r}
source("../rf_functions.R")
```

Splitting the cohorts into the 
```{r}
train.outcomes <- sorting(pt.status,
                          "Adj",
                          "Therapy complete", 
                          "Progression")

train.outcomes <- arrange(train.outcomes, desc(Sample))


test.outcomes <- sorting(pt.status, 
                        "Adj Validation",
                        "Therapy complete",
                        "Progression") 

test.outcomes <- arrange(test.outcomes, desc(Sample))


train.seq <- filter(gene.exp,
                    (Sample %in% train.outcomes$Sample))
train.seq <- arrange(train.seq, desc(Sample))


test.seq <- filter(gene.exp,
                   (Sample %in% test.outcomes$Sample))
test.seq <- arrange(test.seq, desc(Sample))


```

```{r}
train.outcomes <-
  train.outcomes %>%
  select(Sample,
         `Reason.for.discontinuation`)


test.outcomes <-
  test.outcomes %>%
  select(Sample,
         `Reason.for.discontinuation`)
```


```{r}
seed_list <- c(12345:12369)
```

```{r}
rf_rec <- kTest(seed_list, "Therapy complete", "Progression") 

aucprs <- grabVals(aucprs, rf_rec, seed_list)

aucprs_avg <- mean(aucprs$AUCPR)
aucprs_avg

aucprs_max <- max(aucprs$AUCPR)
aucprs_max


p_values <- fishing(p_values, rf_rec, seed_list)

p_values_avg <- mean(p_values$p.value)
p_values_avg

p_values_min <- min(p_values$p.value)
p_values_min


saveRDS(rf_rec, file = "../Outputs/rf_rec.RData")



```


Creating objects for runs, including making a new longer seed list for use in shuffling
```{r}
run_number <- 1:1000
seed_list_r <- c(12345:13344)
rf_rec_random_1000 <- data.frame(run = run_number,
                                 Average_AUCPR = NA,
                                 max_aucpr = NA,
                                 min_aucpr = NA,
                                 sd_aucpr = NA,
                                 first_q_aucpr = NA,
                                 middle_q_aucpr = NA,
                                 third_q_aucpr = NA,
                                 Average_p_value = NA,
                                 max_p_value = NA,
                                 min_p_value = NA,
                                 sd_p_value = NA,
                                 first_q_p_value = NA,
                                 middle_q_p_value = NA,
                                 third_q_p_value = NA
                                 )
rf_rec_random_25000 <- list()
```



```{r}
for (j in 1:length(run_number)) {
  set.seed(seed_list_r[j])

    train.outcomes$Reason.for.discontinuation<-
    (sample(train.outcomes$Reason.for.discontinuation))

  test.outcomes$Reason.for.discontinuation<-
    (sample(test.outcomes$Reason.for.discontinuation))

  rf_random <- kTest(seed_list, "Therapy complete", "Progression")

  rf_rec_random_25000 <- append(rf_rec_random_25000, rf_random)

  aucprs_random <- grabVals(aucprs_random, rf_random, seed_list)
  
  avg_aucpr <- mean(aucprs_random$AUCPR)
  rf_rec_random_1000[j, 2] <- avg_aucpr
  
  
  max_aucpr <- max(aucprs_random$AUCPR)
  rf_rec_random_1000[j, 3] <- max_aucpr
  
  
  min_aucpr <- min(aucprs_random$AUCPR)
  rf_rec_random_1000[j, 4] <- min_aucpr
  
  
  sd_aucpr <- sd(aucprs_random$AUCPR)
  rf_rec_random_1000[j, 5] <- sd_aucpr
  
  
  first_q_aucpr <- quantile(aucprs_random$AUCPR, probs = c(0.25))
  rf_rec_random_1000[j, 6] <- first_q_aucpr
  

  middle_q_aucpr <- quantile(aucprs_random$AUCPR, probs = c(0.5))
  rf_rec_random_1000[j, 7] <- middle_q_aucpr
    

  third_q_aucpr <- quantile(aucprs_random$AUCPR, probs = c(0.75))
  rf_rec_random_1000[j, 8] <- third_q_aucpr
    

  

  p_values_random <- fishing(p_values_random, rf_random, seed_list)
  avg_p_values <- mean(p_values_random$p.value)
  rf_rec_random_1000[j, 9] <- avg_p_values
  
  max_p_value <- max(p_values_random$p.value)
  rf_rec_random_1000[j, 10] <- max_p_value
  
  min_p_value <- min(p_values_random$p.value)
  rf_rec_random_1000[j, 11] <- min_p_value
  
  
  sd_p_value <- sd(p_values_random$p.value)
  rf_rec_random_1000[j, 12] <- sd_p_value
  
  
  first_q_p_value <- quantile(p_values_random$p.value, probs = c(0.25))
  rf_rec_random_1000[j, 13] <- first_q_p_value
  

  middle_q_p_value <- quantile(p_values_random$p.value, probs = c(0.5))
  rf_rec_random_1000[j, 14] <- middle_q_p_value
    

  third_q_p_value <- quantile(p_values_random$p.value, probs = c(0.75))
  rf_rec_random_1000[j, 15] <- third_q_p_value
  
    
}
```


```{r}

saveRDS(rf_rec_random_1000, file = "../Outputs/rf_rec_random_1000.RData")
saveRDS(rf_rec_random_25000, file = "../Outputs/rf_rec_random_25000.RData")

```


```{r}
rec_aucpr_avg <- p.calc(aucprs_avg,
                       rf_rec_random_1000$Average_AUCPR)

rec_aucpr_max <- p.calc(aucprs_max,
                       rf_rec_random_1000$max_aucpr)

rec_p_value_avg <- p.calc(p_values_avg,
                       rf_rec_random_1000$Average_p_value)

rec_p_value_min <- p.calc(p_values_min,
                       rf_rec_random_1000$min_p_value)


rec_aucpr_avg
rec_aucpr_max
rec_p_value_avg
rec_p_value_min
```


```{r}
rf_rec <- readRDS(file = "../Outputs/rf_rec.RData")

rf_rec_random_1000 <- readRDS(file = "../Outputs/rf_rec_random_1000.RData")
rf_rec_random_25000<- readRDS(file = "../Outputs/rf_rec_random_25000.RData")

# test_conmat <- confusionMatrix(rf_tox_random_25000[[3]][[1]][[3]], positive = "Toxicity")
  
# for (j in 1:length(rf_rec)) {
# #   test_conmat <- list()
# # test_conmat2 <- data.frame(Accuracy = NA)
# 
#   test_conmat <- confusionMatrix(rf_tox_random_1000[[j]][[1]][[3]], positive = "Progression")
# test_conmat2[j,1] <- test_conmat[[3]][1]
#   
# }
```

```{r}
source("../rf_functions.R")
```

```{r}
testfile2 <- add.metrics(rf_rec_random_25000, testfile2, "Progression")
```



