---
title: "XGBoost_split_tox"
author: "Noah Lepola"
date: "2024-08-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(xgboost)
library(tidyverse)
library(caret)
library(magrittr)
```

Loading file
```{r}
load(file = "../Outputs/pt.char")
load(file = "../Outputs/pt.status_no_ipi")
load(file = "../Outputs/gene.exp")
```

```{r}
source("../rf_functions.R")

source("../xgb_functions.R")
```




Splitting by cohort and outcome
```{r}


train.outcomes <- sorting(pt.status,
                          "Adj",
                          "Therapy complete", 
                          "Toxicity")

train.outcomes <- arrange(train.outcomes, desc(Sample))


test.outcomes <- sorting(pt.status, 
                        "Adj Validation",
                        "Therapy complete",
                        "Toxicity") 

test.outcomes <- arrange(test.outcomes, desc(Sample))


pt.char <- pt.char %>%
  mutate(
    across(
      .cols = Stage:Sex,
      .fns = as.factor
    )
  )

train.seq <- filter(pt.char,
                    (Sample %in% train.outcomes$Sample))
train.seq <- arrange(train.seq, desc(Sample))


test.seq <- filter(pt.char,
                   (Sample %in% test.outcomes$Sample))
test.seq <- arrange(test.seq, desc(Sample))


train.data <- train.seq %>%
    select(-Sample)

train.label <- train.outcomes %>%
  select(Reason.for.discontinuation) %>% 
  mutate(Reason.for.discontinuation = case_when(
  Reason.for.discontinuation == "Therapy complete" ~ 0, TRUE ~ 1)) 



test.data <- test.seq %>%
    select(-Sample)

test.label <- test.outcomes %>%
  select(Reason.for.discontinuation) %>% 
  mutate(Reason.for.discontinuation = case_when(
  Reason.for.discontinuation == "Therapy complete" ~ 0, TRUE ~ 1))

# Use model.matrix to create a one-hot encoded numeric matrix
# -1 removes the Intercept column which xgboost doesn't need
train_matrix <- model.matrix(~ . - 1, data = train.data)
test_matrix <- model.matrix(~ . - 1, data = test.data)


xgb.train <- xgb.DMatrix(data = train_matrix,
                         label = train.label$Reason.for.discontinuation)

xgb.test <- xgb.DMatrix(data = test_matrix,
                        label = test.label$Reason.for.discontinuation)

```


```{r}

xgb_tox <- data.frame(run = 1, F1 = NA)

watchlist = list(train=xgb.train, test=xgb.test)

bst <- xgb.train(data = xgb.train,
                    max.depth = 3,
                    eta = 0.1,
                    nrounds = 100,
                    watchlist = watchlist,
                    verbose = 0,
                    objective = "binary:logistic",
                    eval_metric = 'aucpr',
                    scale_pos_weight = 1,
                    early_stopping_rounds = 25)


pred <- predict(bst, xgb.test)

pred <-  as.numeric(pred > 0.5)

test.label.vector <- as.vector(test.label$Reason.for.discontinuation)

bop100 <- confusionMatrix(factor(pred), factor(test.label.vector), positive = "1")
xgb_tox$F1 <- bop100[[4]][7]
print(bop100[[4]][7])
importance_matrix <- xgb.importance(model = bst)
print(importance_matrix)
xgb.plot.importance(importance_matrix = importance_matrix)


```

```{r}
run_number <- 1:1000
seed_list <- c(12345:13344)

xgb_tox_random <- data.frame(run = run_number, F1 = NA)
```

```{r}

for (i in 1:length(run_number)) {
  
set.seed(seed_list[i])

train.label$Reason.for.discontinuation<- 
  (sample(train.label$Reason.for.discontinuation))
  

test.label$Reason.for.discontinuation<- 
  (sample(test.label$Reason.for.discontinuation))


xgb.train <- xgb.DMatrix(data = train_matrix,
                         label = train.label$Reason.for.discontinuation)

xgb.test <- xgb.DMatrix(data = test_matrix,
                        label = test.label$Reason.for.discontinuation)

watchlist = list(train=xgb.train, test=xgb.test)

  
randommodel <- xgb.train(data = xgb.train,
                    max.depth = 3,
                    eta = 0.1,
                    nrounds = 100,
                    watchlist = watchlist,
                    verbose = 0,
                    objective = "binary:logistic",
                    eval_metric = 'aucpr',
                    scale_pos_weight = 1,
                    early_stopping_rounds = 25)

randompred <- predict(randommodel, xgb.test)

randompred <-  as.numeric(randompred > 0.5)

test.label.vector <- as.vector(test.label$Reason.for.discontinuation)

suppressWarnings(
randomcm <- confusionMatrix(factor(randompred), factor(test.label.vector), positive = "1")
)
xgb_tox_random$F1[i] <- randomcm[[4]][7]
# print(randomcm[[4]][7])
# print(i)
}
# write_csv(xgb_tox_aucpr, file = "xgb_tox_random_1000")
```


```{r}
xgb_tox_random$F1[is.na(xgb_tox_random$F1)] <- 0

p.calc(xgb_tox$F1, xgb_tox_random$F1)
```


```{r}
metrics_plot <- ggplot(data = xgb_tox_random, aes(x = F1)) + 
  geom_density() +
  geom_vline(xintercept = xgb_tox$F1, color = "red") + 
  theme(
    axis.title.x = element_text(size = 18, face = "bold"), # X title only
    axis.title.y = element_text(size = 18, face = "bold"), # Y title only
    axis.text.x = element_text(size = 14),  # X numbers only
    axis.text.y = element_text(size = 14)   # Y numbers only
  )

print(metrics_plot)


# 1. Generate the plot
metrics_plot <- ggplot(data = xgb_tox_random, aes(x = F1)) +
  # Create the distribution curve for the 1000 random values
  geom_density(fill = "skyblue", alpha = 0.4, linewidth = 0.75) + 
  
  # Add the single observed value as a vertical line
  geom_vline(aes(xintercept = xgb_tox$F1), 
             color = "red", 
             linetype = "dashed", 
             linewidth = 1) +
  
  # Add a label for the red line so it's clear what it represents
  annotate("text", x = xgb_tox$F1, y = 0.5, label = "Observed F1", 
           color = "red", angle = 90, vjust = -0.5) +
  
  # Apply labels and custom font sizes
  labs(title = "Distribution of Random F1 vs. Observed Value",
       x = "F1 Score",
       y = "Density") +
  theme_minimal() +
  theme(
    axis.title = element_text(size = 16), # Font size for 'F1 Score' and 'Density'
    axis.text = element_text(size = 12),  # Font size for the numbers
    plot.title = element_text(size = 18, face = "bold")
  )

print(metrics_plot)

#Empirical P-value script
# p_value <- sum(xgb_tox_random$F1 >= xgb_tox$F1) / nrow(xgb_tox_random)
# print(paste("Empirical P-value:", p_value))

```

